In [34]:
import numpy as np
import cv2

In [35]:
# Load an color image in grayscale
img = cv2.imread('messi.jpg',0)
img = cv2.line(img, (0, 0), (500, 500), (255, 0, 0), 5)
print(img)

[[255 255 255 ...  22  22  22]
 [255 255 255 ...  21  21  21]
 [255 255 255 ...  19  19  19]
 ...
 [ 36  36  37 ...  41  41  40]
 [ 36  36  37 ...  41  41  40]
 [ 36  36  37 ...  41  41  40]]


In [36]:
def drawc(event,x,y,flags,param):
    if event == cv2.EVENT_LBUTTONDBLCLK:
        cv2.circle(img, (x, y), 30, (200, 100, 0), -1)

cv2.namedWindow('image')
cv2.setMouseCallback('image', drawc)


In [37]:
while(1):
    cv2.imshow('image',img)
    if cv2.waitKey(20) & 0xFF == 27:
        break
cv2.destroyAllWindows()

In [21]:
import cv2
import numpy as np

# mouse callback function
def draw_circle(event,x,y,flags,param):
    if event == cv2.EVENT_LBUTTONDBLCLK:
        cv2.circle(img,(x,y),100,(255,0,0),-1)

# Create a black image, a window and bind the function to window
img = np.zeros((512,512,3), np.uint8)
cv2.namedWindow('image')
cv2.setMouseCallback('image',draw_circle)

i = 0
while(1):
    cv2.imshow('image',img)
    i += 1
    if i%100 == 0:
        print(i)
    if cv2.waitKey(20) & 0xFF == 27:
        break
cv2.destroyAllWindows()

In [19]:
img = cv2.imread('messi.jpg',0)
cv2.imshow('image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

AttributeError: module 'cv2.cv2' has no attribute 'EVENT_LBUTTONDBLCLCK'

AttributeError: module 'cv2.cv2' has no attribute 'EVENT_LBUTTONDBLCLCK'

AttributeError: module 'cv2.cv2' has no attribute 'EVENT_LBUTTONDBLCLCK'

AttributeError: module 'cv2.cv2' has no attribute 'EVENT_LBUTTONDBLCLCK'

AttributeError: module 'cv2.cv2' has no attribute 'EVENT_LBUTTONDBLCLCK'

AttributeError: module 'cv2.cv2' has no attribute 'EVENT_LBUTTONDBLCLCK'

AttributeError: module 'cv2.cv2' has no attribute 'EVENT_LBUTTONDBLCLCK'

AttributeError: module 'cv2.cv2' has no attribute 'EVENT_LBUTTONDBLCLCK'

AttributeError: module 'cv2.cv2' has no attribute 'EVENT_LBUTTONDBLCLCK'

AttributeError: module 'cv2.cv2' has no attribute 'EVENT_LBUTTONDBLCLCK'

AttributeError: module 'cv2.cv2' has no attribute 'EVENT_LBUTTONDBLCLCK'

AttributeError: module 'cv2.cv2' has no attribute 'EVENT_LBUTTONDBLCLCK'

AttributeError: module 'cv2.cv2' has no attribute 'EVENT_LBUTTONDBLCLCK'

AttributeError: module 'cv2.cv2' has no attribute 'EVENT_LBUTTONDBLCLCK'

AttributeError: module 'cv2.cv2' has no attribute 'EVENT_LBUTTONDBLCLCK'

AttributeError: module 'cv2.cv2' has no attribute 'EVENT_LBUTTONDBLCLCK'

AttributeError: module 'cv2.cv2' has no attribute 'EVENT_LBUTTONDBLCLCK'

AttributeError: module 'cv2.cv2' has no attribute 'EVENT_LBUTTONDBLCLCK'

AttributeError: module 'cv2.cv2' has no attribute 'EVENT_LBUTTONDBLCLCK'

AttributeError: module 'cv2.cv2' has no attribute 'EVENT_LBUTTONDBLCLCK'

AttributeError: module 'cv2.cv2' has no attribute 'EVENT_LBUTTONDBLCLCK'

AttributeError: module 'cv2.cv2' has no attribute 'EVENT_LBUTTONDBLCLCK'

AttributeError: module 'cv2.cv2' has no attribute 'EVENT_LBUTTONDBLCLCK'

AttributeError: module 'cv2.cv2' has no attribute 'EVENT_LBUTTONDBLCLCK'

AttributeError: module 'cv2.cv2' has no attribute 'EVENT_LBUTTONDBLCLCK'

AttributeError: module 'cv2.cv2' has no attribute 'EVENT_LBUTTONDBLCLCK'

AttributeError: module 'cv2.cv2' has no attribute 'EVENT_LBUTTONDBLCLCK'

AttributeError: module 'cv2.cv2' has no attribute 'EVENT_LBUTTONDBLCLCK'

AttributeError: module 'cv2.cv2' has no attribute 'EVENT_LBUTTONDBLCLCK'

AttributeError: module 'cv2.cv2' has no attribute 'EVENT_LBUTTONDBLCLCK'

AttributeError: module 'cv2.cv2' has no attribute 'EVENT_LBUTTONDBLCLCK'

AttributeError: module 'cv2.cv2' has no attribute 'EVENT_LBUTTONDBLCLCK'

AttributeError: module 'cv2.cv2' has no attribute 'EVENT_LBUTTONDBLCLCK'

AttributeError: module 'cv2.cv2' has no attribute 'EVENT_LBUTTONDBLCLCK'

AttributeError: module 'cv2.cv2' has no attribute 'EVENT_LBUTTONDBLCLCK'

AttributeError: module 'cv2.cv2' has no attribute 'EVENT_LBUTTONDBLCLCK'

AttributeError: module 'cv2.cv2' has no attribute 'EVENT_LBUTTONDBLCLCK'

AttributeError: module 'cv2.cv2' has no attribute 'EVENT_LBUTTONDBLCLCK'

AttributeError: module 'cv2.cv2' has no attribute 'EVENT_LBUTTONDBLCLCK'

AttributeError: module 'cv2.cv2' has no attribute 'EVENT_LBUTTONDBLCLCK'

AttributeError: module 'cv2.cv2' has no attribute 'EVENT_LBUTTONDBLCLCK'

AttributeError: module 'cv2.cv2' has no attribute 'EVENT_LBUTTONDBLCLCK'

AttributeError: module 'cv2.cv2' has no attribute 'EVENT_LBUTTONDBLCLCK'

AttributeError: module 'cv2.cv2' has no attribute 'EVENT_LBUTTONDBLCLCK'

AttributeError: module 'cv2.cv2' has no attribute 'EVENT_LBUTTONDBLCLCK'

AttributeError: module 'cv2.cv2' has no attribute 'EVENT_LBUTTONDBLCLCK'

AttributeError: module 'cv2.cv2' has no attribute 'EVENT_LBUTTONDBLCLCK'

AttributeError: module 'cv2.cv2' has no attribute 'EVENT_LBUTTONDBLCLCK'

AttributeError: module 'cv2.cv2' has no attribute 'EVENT_LBUTTONDBLCLCK'

AttributeError: module 'cv2.cv2' has no attribute 'EVENT_LBUTTONDBLCLCK'

AttributeError: module 'cv2.cv2' has no attribute 'EVENT_LBUTTONDBLCLCK'

AttributeError: module 'cv2.cv2' has no attribute 'EVENT_LBUTTONDBLCLCK'

AttributeError: module 'cv2.cv2' has no attribute 'EVENT_LBUTTONDBLCLCK'