In [1]:
import cv2
import numpy as np
import time as t

In [2]:
cv2.destroyAllWindows()

In [3]:
img = cv2.imread('messi.jpg', 3)
cv2.imshow('image', img)
cv2.waitKey(20)

-1

In [4]:
cv2.destroyAllWindows()


In [5]:
img1 = cv2.imread('trans1.jpg')
img2 = cv2.imread('trans2.jpg')
cv2.namedWindow('si')
def no(x):
    a = 0
cv2.createTrackbar('trans', 'si', 0, 100, no)
print(img1)
print(img2)
over = True

while over:
    maxi = 100
    for i in range (maxi):
        koef1 = cv2.getTrackbarPos('trans', 'si')/100
        koef2 = 1-koef1
        img = cv2.addWeighted(img1,koef1,img2,koef2,0)
        cv2.imshow('si', img)
        if cv2.waitKey(10) == 27:
            over = False
            break

cv2.destroyAllWindows()

[[[153 110  47]
  [153 110  47]
  [154 111  48]
  ...
  [163 135 101]
  [163 135 101]
  [164 136 102]]

 [[153 110  47]
  [153 110  47]
  [154 111  48]
  ...
  [161 133 102]
  [162 133 102]
  [162 134 103]]

 [[153 110  47]
  [153 110  47]
  [154 111  48]
  ...
  [160 133 106]
  [162 133 106]
  [160 133 106]]

 ...

 [[104 138 232]
  [ 93 131 225]
  [ 57 101 194]
  ...
  [  6  14  21]
  [  7  15  22]
  [  9  17  24]]

 [[ 96 129 226]
  [ 95 133 229]
  [ 51  97 192]
  ...
  [ 10  16  23]
  [  8  16  23]
  [ 10  18  25]]

 [[ 99 132 229]
  [100 138 234]
  [ 79 125 220]
  ...
  [ 11  17  24]
  [  9  17  24]
  [  9  17  24]]]
[[[184 174 120]
  [189 177 123]
  [192 178 125]
  ...
  [187 170 237]
  [185 170 231]
  [188 175 229]]

 [[188 175 123]
  [190 178 124]
  [192 178 125]
  ...
  [187 170 237]
  [186 171 232]
  [189 176 230]]

 [[190 176 127]
  [192 178 125]
  [194 179 123]
  ...
  [187 170 237]
  [187 172 233]
  [190 177 231]]

 ...

 [[178 151 207]
  [174 148 208]
  [174 147 211]
  ..

In [194]:
cv2.useOptimized()

True

## 

In [201]:
x = 4
%timeit res = cv2.medianBlur(img1, 49)

10 loops, best of 3: 23.9 ms per loop


In [6]:
import cv2
import numpy as np
import time

cap = cv2.VideoCapture(0)
last_print = 0
while(1):

    times = time.time()
    # Take each frame
    _, frame = cap.read()

    # Convert BGR to HSV
    hsv = cv2.cvtColor(frame, cv2.COLOR_BGR2HSV)

    # define range of blue color in HSV
    lower_blue = np.array([90,50,50])
    upper_blue = np.array([150,255,255])

    # Threshold the HSV image to get only blue colors
    mask = cv2.inRange(hsv, lower_blue, upper_blue)

    # Bitwise-AND mask and original image
    res = cv2.bitwise_and(frame,frame, mask= mask)

    cv2.imshow('frame',frame)
    cv2.imshow('mask',mask)
    cv2.imshow('res',res)
    k = cv2.waitKey(1) & 0xFF
    if k == 27:
        break
    fps = 1/ (time.time()-times)
    if time.time()-last_print > 2:
        print(fps)
        last_print = time.time()
cv2.destroyAllWindows()
cap.release()

3.643403216629532
29.65828271614541
30.007970065749465
32.76185715178404
29.615771338191266
30.462378711289293
23.477246521208592
31.323684485668622
29.462244138182943
29.928103549155882
29.068570240487908
35.86775898339291
28.578366776820086
34.53437955423085
29.929171334584453
31.16726856599343
28.365574236132716
29.478809687803096


In [2]:
green = np.uint8([[[0, 255, 0]]])
green = cv2.cvtColor(green, cv2.COLOR_BGR2HSV)
green

array([[[ 60, 255, 255]]], dtype=uint8)

In [9]:
cap.release()
cv.destroyAllWindows()

In [1]:
def no(x):
    a = 7

In [2]:
print("jello")

jello


In [20]:
import numpy as np 
import cv2 as cv
import time as t

cap = cv.VideoCapture(0)
cap.set(3,320);
cap.set(4,240);
low = np.array([100, 50, 50])
high = np.array([150, 255, 255])
cv.namedWindow('low')
cv.createTrackbar('h', 'low', 0, 179, no)
cv.createTrackbar('s', 'low', 0, 255, no)
cv.createTrackbar('v', 'low', 0, 255, no)
cv.namedWindow('high')
cv.createTrackbar('h', 'high', 0, 179, no)
cv.createTrackbar('s', 'high', 0, 255, no)
cv.createTrackbar('v', 'high', 0, 255, no)

lowi = np.zeros((200, 200, 3), np.uint8)
highi = np.zeros((200, 200, 3), np.uint8)
while True:
    t1 = t.time()
    _, frame = cap.read()
    h = cv.getTrackbarPos('h', 'low')
    s = cv.getTrackbarPos('s', 'low')
    v = cv.getTrackbarPos('v', 'low')
    low = np.array([h, s, v])
    lowi[:] = [h, s, v]
    lowi = cv.cvtColor(lowi, cv.COLOR_HSV2BGR)
    
    h = cv.getTrackbarPos('h', 'high')
    s = cv.getTrackbarPos('s', 'high')
    v = cv.getTrackbarPos('v', 'high')
    high = np.array([h, s, v])
    highi[:] = [h, s, v]
    highi = cv.cvtColor(highi, cv.COLOR_HSV2BGR)
    hsv = cv.cvtColor(frame, cv.COLOR_BGR2HSV)
    mask = cv.inRange(hsv, low, high)
    cv.imshow('mask', mask)
    cv.imshow('image', frame)
    cv.imshow('high', highi)
    cv.imshow('low', lowi)
    k = cv.waitKey(1)
    if k != 255:
        break
    print(1/(t.time()-t1))
    
cv.destroyAllWindows()
cap.release()


2.00333004404714
31.40483392734134
43.78644952500261
28.513089645889558
38.00324372321437
45.335495098198166
14.788828438752807
24.846006208089474
35.324024322457845
30.48053137217854
13.693763814386879
39.01024944660429
20.885887859774922
12.817406451021437
35.91013698630137
37.021413314032515
31.997802885238897
37.0181458730495
36.54784684825988
17.052858403229806
31.590988860351437
25.452572683856324
16.297419956481193
21.218288697552538
26.454808068320865
28.794376098418276
30.709953286766535
34.745508014745475
32.00317414294325
28.076579109433155
31.991213350825273
43.046758898148525
36.17619306371344
37.55846481723588
31.263213601568264
35.82854116481301
36.28259271113572
45.10101292500914
40.07820129379951
37.548041717022514
24.72065445458189
35.625256935124945
36.724811529739334
33.46634857056228
37.65591417156709
38.90278718174651
37.94582662348237
30.856352534392702
31.47364629607396
35.55218010442802
28.01132660148528
37.47959502810319
34.64048033960737
30.060446215482084
31

37.028930617722104
28.947196245557127
34.17087457737586
35.39795763355558
32.585976770384185
29.388340807174888
37.21786043870235
35.53952786863021
35.885864868795935
36.45160561421805
31.050518211430262
28.50417609601283
22.798351941035147
33.46314454169027
29.67737918347131
34.115287323599986
31.660142362185706
32.537694133709834
36.07227692969254
29.856947608200457
29.84335154826958
25.51202214044585
28.674296183874098
34.45324834276608
34.87319681058924
37.75115207373272
30.680076950647717
30.693772411269666
27.472287357375848
33.31668414196295
29.235322408637526
36.62315980650682
32.05723107965576
36.55995258184861
32.49559551571591
28.66959220221739
27.144963272174223
25.495893841674317
37.144360116543716
37.73620757908375
32.533908362485555
30.362264915811267
23.162840528167266
31.688606829857964
34.75356914994987
31.454527728823727
32.994060870180846
28.27169597659699
34.16280319937446
28.38899718431882
30.991783413134716
23.214762500415112
30.99980044493389
32.04571952477366
3

27.06893235838889
27.130916265079726
32.20837940778966
32.846523720769966
19.864096613781673
20.82532621000576
29.351117207017445
28.004780631764493
26.97492427117031
30.13972205055978
32.74369803661345
32.76313672189284
33.71816742099636
19.77559112661779
27.013144929123005
32.5847110006215
31.9449191914576
32.7082053121637
33.05907482285435
33.16940158638524
29.863537654237483
32.443564356435644
30.052261637779704
29.499335363580737
33.91693621425799
34.09033201934409
34.32523958000868
33.4428665970323
28.125152551465163
24.145715798926936
33.77409873819321
33.90816194541456
34.145003988993636
33.92077638495754
31.844992787183966
32.14272358035098
30.536675573158213
32.66668224335459
34.38799704845454
33.313508705045116
34.11584230090367
32.35596698295148
29.28512878518115
32.249240729207514
33.64432964882165
28.67468825202363
36.63243578434369
34.04329369749604
27.23945473083992
29.34413544618183
26.532793522267205
33.578070961957216
30.88429904202287
34.537223224063965
34.757889154

30.14752095223035
30.79405308175177
29.091958328131287
26.17938507246558
33.968576889436
35.022870932456016
33.070022313156876
26.34199403360025
27.825496231822523
27.02689606289065
28.84150014440334
32.44808218966131
30.895218733196327
25.64272744502253
28.46722502002199
23.27130690487419
32.89779207027727
29.850997807953995
32.498616933078154
36.19273781582217
29.898236459803545
30.11397103696843
30.120675044883303
34.70095143542649
34.59904640918615
34.68889771073177
34.52869361915817
33.05073874157834
35.01176156331127
32.792081684987416
29.041398649818245
19.512565479125765
28.53035126384241
30.70748010454722
28.29458232425103
31.556525271980377
30.528896264593705
32.91044050029032
34.34828967087322
35.29043928953059
32.70718507774607
31.966100403167417
32.44481918391027
27.28410754129073
31.1934613010464
31.679272502058172
26.55917124168107
21.95901699423055
33.789879883024916
28.33319147498902
33.468751994893076
35.2604748133701
35.60106608722223
36.26408438526716
29.87140700225

25.301795850902753
32.98679522772137
25.886610790860725
29.211093003496163
25.749303210755723
27.531254307600413
30.636378244927176
29.80411997527162
30.131710716312618
27.55929352396972
31.536831657856943
25.477619102577343
21.228275998198207
29.47735945856672
27.89953171562367
27.23874713442393
17.44537381719871
27.49461815798099
25.48783733691458
24.506166996780657
26.641327269493637
26.45948094222738
29.22839562093644
25.26110890278129
25.249703515077087
24.901469994537983
29.963380744529616
26.524236234514422
24.68675287373235
21.247417719082282
21.969253654729542
25.810466203908828
20.532132367338946
21.847153929494123
24.345431644445476
22.665665140961142
23.722365503823358
24.35221644845705
24.272873528628804
26.1633814062578
25.015530691604837
33.84741522619797
28.703534644995724
23.680578139114726
26.796726359704326
23.25633902778471
23.251568840499367
28.596487400458166
18.90654694289681
27.52727917095997
22.44755925908086
24.499009947255598
25.45643465805637
24.151555284281

29.74725882636633
22.56907174335326
24.97635338323478
33.36491925861109
31.62815108624343
31.641751410724524
28.424974755518207
25.167132690899926
31.16726856599343
24.871052288279312
31.5819497466248
27.772249627545108
28.86114761881825
24.232485585200422
21.351252017124562
16.30324797487445
29.545882966208552
21.12595069961418
26.584927425999872
28.620098122837785
29.213127542207612
28.9669880383436
28.007585672694248
31.696030348600836
25.854696534464267
31.978530039646234
30.82868315056008
29.001438212191616
32.09574459944445
29.62162772959688
30.602178623804345
20.724996170551293
27.204119886625286
33.34343474493406
32.31209651325825
31.944432597105866
34.480155206997466
32.10016607608887
32.13976797290463
29.77175224656095
30.359407911403856
28.58265130193604
29.52321423543655
31.751937984496124
31.969755175462666
29.900367846245974
34.371089076456606
26.632530732500253
35.30915580698387
27.74909858353567
30.069713089485685
31.525690748925168
31.976092094228864
31.34287849349873


26.969373910918783
30.596374512163987
29.5138657265697
33.8898055153802
25.43806214103334
34.56226772691689
32.88721615857484
19.148925290819776
28.49526811736971
30.119377262021025
32.810294520280046
34.841331417226684
34.55771147967801
34.68574216650265
31.806354743307804
33.43406935033878
28.93681138623083
31.60622433216533
36.03106315717133
35.82425691834643
24.835560713630148
28.447338257336835
25.686226958172576
34.08506834397907
33.44100012756729
34.2107306569224
34.77287348698392
28.78410057920887
29.444250222886787
32.388948091862424
25.900198220339508
34.06043380460115
31.312459873086972
33.597974975568334
32.14592610191835
27.489572546500806
26.182653532591733
35.18003086626854
33.534847648973
33.277298656786286
24.006685211259544
33.919679104598316
31.75650567472005
31.92060761959847
32.36245794882874
35.420975737461255
31.38579884313476
28.653531903265474
32.978236256132845
29.520928497526025
29.200314677768574
25.161546537088697
25.699289858890857
36.98387253216235
33.976

31.79791516621811
34.21352127381885
24.906497547535064
33.75317066889848
33.56597869667166
34.05849776695087
30.39086456250181
23.782491593946506
36.027658715501765
26.52591369900266
28.59453784377088
29.091352989727906
34.60075895066821
35.9553890598613
25.2551768155735
27.457719878236393
30.663703357117793
34.07094756508671
34.856387796993296
34.32299244687032
25.104618939026654
25.373429399345444
33.03538010774708
26.703236116151295
29.404411043030805
33.9589510246051
33.88925786773321
28.65901388433366
28.250749324765774
31.222022063749648
34.834386705091894
34.07094756508671
32.91095696933555
34.532957894910176
32.34299285945621
32.66032299761723
26.274502925441947
31.38791271290448
33.40557675000199
26.182816977021467
37.645774805905845
29.16437670356567
34.95165954184479
32.51146422757926
34.846831278455355
37.66572075146377
34.20570869352471
36.51857140369513
26.89915152603462
35.140829612004325
26.341332294996516
29.026526135128965
34.07454586813115
34.51704330365225
33.056990

34.377286735296046
27.63046113306983
27.7588320163073
31.67472700086091
32.146665235985715
32.0205209637524
33.25249930629881
32.02687802568684
32.26015459754644
21.77207935799342
31.655124528301886
33.69216557286186
33.570814557504065
34.146393884379606
29.35543113101904
32.12032378370513
26.178568084933747
27.563459048820718
25.14706429003963
31.06431639757073
27.511570551503386
28.35713609627476
31.797191982290688
28.1221353573009
29.725544113790832
28.230023691578722
35.56695243667693
31.30731794703371
30.0004577706569
29.756122477936376
31.930327806452595
34.07925248832013
34.77200865506578
34.92226736828082
33.19775531687549
33.24116723993089
28.531709805788918
35.213997263011194
37.531578288025486
35.845994752540406
23.281770041186984
26.84835682554314
35.66463725723615
30.289906984805594
33.98013513294554
36.17681711934724
33.69243621875201
34.70985360686533
34.56369180057684
29.662687411598302
27.955131067669974
29.70154728605318
36.52365941587279
37.36107746027221
34.55714203

25.02702412420715
30.156191133543274
33.090372614454886
34.48213948058568
34.80259216542065
34.006859255535645
29.48399024301089
21.833961478396667
32.60979155814369
31.951489666415277
34.334512115258676
35.558208145410156
35.32580938584375
35.44102884761631
31.197637660569907
31.657991667169856
29.276747822202367
35.9452205063161
35.25306571858427
35.25573263398561
35.49171158516462
27.50886398069141
28.590249754607918
29.670241362723182
35.801934222768516
35.32551186275088
35.28925160910353
35.714441416893735
29.69271611318377
31.806354743307804
30.442258979960663
33.00678344901396
35.403335809305155
35.719612001056014
35.38004217629692
21.50285556091009
32.18292448993685
30.259532071769197
34.06292331931067
33.92571502523619
34.95748564379954
28.74779986291981
26.541356333331223
31.273470179022794
27.92962829784117
31.59479635111824
23.242034334098037
34.37475105927862
33.42980568440853
34.63618946951179
32.144940642698934
28.026674863351463
30.116133294081322
35.21429291063573
35.0

25.564112878649357
29.63606944257986
33.654047982026796
33.890627020038785
34.11917254394742
33.272283039822305
33.63461692675338
32.27057927415694
26.335378143345995
31.48782318849284
24.15322422748684
33.182784810126584
35.09789712392158
35.3329514438791
32.11860201549913
31.688128012571585
29.00123768366465
34.455512564589135
35.337118978212885
34.739464617015635
35.38272833871825
26.329591964846202
30.07920138839087
30.859076796303654
35.52778742471857
30.128031260774623
24.072268965438077
36.164651916742834
30.757696199932536
32.37394834745828
24.720071667688245
31.560799422104502
34.55913517789167
35.09378582126392
34.2996957901279
27.5020097174593
27.791939993903974
29.138037875314353
34.974683966512124
32.13287366888838
32.15824944221672
27.729285530117217
23.626687095829297
31.67640150742763
30.92779613025012
34.856967148401466
33.896652604697024
33.205114198630405
25.695668688353855
29.67234036532394
33.001849039679605
22.407744375764633
32.32355117139334
34.48809367188528
33

28.56377008989376
31.021581882460836
28.8278222619334
31.505798930352743
33.18908653541812
32.811577876867716
33.323036832236944
28.836939408314944
18.79783262446947
33.65350792733808
31.548455035051298
34.44532590931862
34.97001834250459
33.64540918644013
31.59432036458137
31.79526365262743
30.144270919427058
31.62672015322088
34.675705616825674
34.101973283032365
33.87092189417921
27.57052520870308
31.435903585561817
28.308714051416345
26.076844644500262
35.804379188185585
33.98261292282763
32.10016607608887
31.2166774584887
29.88162206833661
30.516013561689682
28.604678442337857
34.144726023494165
30.275476764497828
28.183359987098683
30.346667824300173
26.194753934549087
33.95812620431692
34.51960001646023
31.436139196390428
23.353455715725413
31.323216632811565
32.53996601937982
33.13010165796479
32.81209124761398
29.988445918892637
29.25775511485313
30.75927514868839
28.363656036138387
31.467743024555666
31.02800751601592
26.340505168494165
34.000243188690106
34.75270527798492
28

21.172339641499622
33.1081343489758
34.81443607025466
33.60685869957133
31.679272502058172
31.137652002197445
32.618160326002425
30.07941710113955
29.549213416653163
31.040407329563955
26.364015789606015
34.06735002193018
34.092271677992
33.43140443169138
27.60082388476142
27.910299578115225
28.815543051862843
34.04108332724631
34.882767797737856
30.787046008397194
28.68488578853782
30.805361536484153
33.01639679778332
25.83765469744291
35.18563818631769
31.154998625832857
34.92430285519205
30.448888921153692
27.778135410250805
31.553201733269137
25.294166601335174
33.48825919982115
35.04101188835142
33.84659581507573
28.995223117071653
27.977694175404892
30.8019681280752
27.890626662410895
34.80779093602437
34.49319890129772
29.11841602854703
34.022030791194176
29.636697662587263
28.538504456691843
26.770900085527913
31.071220090377064
34.691193012638124
33.90651727538763
30.27722514978705
25.18148688484237
30.26062363822634
28.547245193125743
33.92461742534537
35.067672190358344
29.0

22.702715576268343
30.573848643447583
27.351540287450767
33.57995276410072
35.949841863016516
36.02023307541029
35.85120350109409
34.374187626517184
35.81599733576985
32.45737279938093
30.73560792589987
32.38394663290045
35.68678901736563
36.95356910010396
35.63494248186097
34.38320476772115
33.40557675000199
35.36005800180413
33.314567116759335
36.29420926932263
36.62539840550476
34.5859225542582
32.19008733825538
34.169482688391035
29.44941863730832
36.281337312399984
35.28390803630766
28.584404432510528
32.46340198605274
27.03247012722515
29.07360759713028
30.591688182865813
28.37574502919229
36.194924103174806
36.809899512922904
24.389742396929698
22.679759484362158
29.473216732603
34.406897287187356
36.388672959466966
36.039112577546355
36.63243578434369
26.062423493006406
35.66130170471453
27.674580028767863
31.94467589242873
35.56876213736315
27.255562487003534
33.804041039032214
28.466452199644365
30.19722528204353
26.128990861122706
28.82504862242198
35.18357212361172
36.17806

30.81486705898775
28.409379698993483
32.2455217799099
32.14198462752791
31.86483119093202
33.16363176330126
33.17412384424952
25.96593842667971
30.061954387121745
25.641316574558616
32.22124573641029
29.32669556705356
34.23642151661089
34.548033441785755
21.30072266884703
23.79287967143927
35.65160182580091
36.008482070037175
35.62011362960824
35.51755849302656
35.3439677764576
33.78362007861331
27.187896623474277
27.45394564591297
32.37419822935079
34.45155037167851
33.79096878147029
27.794150000662665
32.4232496656643
30.542457055058364
22.66946276078262
36.21586336712315
34.48695938168064
34.424123044598744
32.9091493985924
26.48688381727017
29.960384299439266
30.01204974455114
34.85378095396377
33.41036649965349
30.491610689464654
26.646912701790946
29.87821627012395
28.475535490003054
32.041068263765816
34.788159280731875
25.388942022493673
35.17590030023985
32.502394494986284
30.61289969418514
25.177254473530983
32.38619709827116
33.993078687381974
33.757245531151156
28.666261148

23.146351154474416
33.13010165796479
31.242720616168462
31.830492524853913
31.976579653574042
35.341883078582384
30.44181708653588
28.82821853972356
29.02431665628676
35.32104961767777
32.17403711175717
30.38051847398576
29.43577794932978
28.46838432926995
32.785417252915614
30.86316409124356
22.03527279413696
36.10923241158442
35.140829612004325
34.91209349170544
29.91657631954351
28.985004077232457
30.993615511941357
29.00524878116248
28.783705513388874
31.31643433657127
34.843068027945534
33.967201431799225
25.593907700193434
33.607397258078734
33.599320692445104
30.64174982831928
22.93586189171602
36.32438424498562
34.79421963399864
28.85737481595641
30.22181231265852
26.79296049059376
30.480974390279354
34.769414417401684
33.91666194962196
30.369299833466076
30.27198059962181
36.36059747037355
34.71358813500405
29.74472732430324
30.7405637560282
30.523786305317625
20.930078444679534
36.65068157986718
35.26492176530432
31.370071202058277
28.606434276126883
30.41466527439378
34.7691

24.742090950383727
18.844537097774225
29.55254461800785
23.19370928676495
31.17097459831448
27.333715656118034
24.417287630402384
25.837973030413167
26.277959815303266
25.644922441043576
22.55608496907771
20.98327063155367
28.69685753186598
24.972338322675906
23.129247499200407
25.64758829860092
29.990375746308676
25.06561168448543
16.881204217982773
16.698466034182793
29.221472114815203
26.705106328791544
22.698906808096115
25.605626236233547
26.147560298985717
29.011869518302298
23.25917628334877
21.198556540549284
21.645004309076928
28.00833377851381
25.76717840972619
26.280429579318035
27.710599163589034
20.8123058601697
16.949490622689012
24.382936669418317
25.710317095447383
25.435285413672446
20.296165106094698
26.8118004282929
22.558875257493533
24.801783422918405
26.687095173256303
25.40308884985767
24.154615189698465
30.74867674442473
27.066836171681906
24.06992051877995
26.89449453043846
29.09054591104237
14.33322853588857
24.990044030290935
25.549474915328574
31.53920308000

25.450410490100303
28.94300146291645
25.54418446022485
30.984457183381597
26.39304794326598
21.05151575988757
17.10264513156339
30.97804957310408
30.37325840743852
30.606868167953415
27.079592996229533
30.242513825898232
26.551269228334494
26.236701196016615
30.935551916921124
25.437445038117012
17.551298467615723
24.248736775163323
25.90995799357549
29.904631530914898
28.333574270601826
25.789359124922374
16.033762500382274
25.84465983523221
24.335402717662486
21.99044737932083
25.185115798701805
19.634416253159817
23.04132195084435
28.77442458752101
21.913814002089865
27.446939109380622
27.688830208608397
26.365838786530134
24.662511466001835
25.64068957085218
32.02272119958161
25.045106586254253
17.270673688631582
27.185958180474714
21.53708382114322
19.67494136410545
23.691011172490143
23.99418780927319
24.28172634382146
28.29897310645418
25.925973544319447
19.795751348647105
27.414289169068674
25.16970013382061
24.96431207294717
29.861198917841378
23.250408820545797
24.71978028454

33.29499738041183
36.67151038251366
24.721820110809855
23.459388108954638
25.39155492326785
21.767220754687607
19.179309430286846
20.77056478569837
15.074193873003551
23.3560565984152
18.75395821130432
22.52519534921189
19.277508904975296
21.888768859037988
18.53344527418143
24.102979036410446
31.704655575124914
21.283428646819136
22.765930654160968
22.688101780730033
30.857487585065293
25.444697888861928
28.839715336748377
26.44780185133806
18.752029757859724
31.15384158298176
32.35796392587678
25.474060127543275
24.798117513509677
25.518541277538134
27.206766819750396
23.72706239074972
22.70148680172549
22.305381833652415
30.280722526242833
33.58640625875834
32.59661312007958
31.698665336537736
33.306366184656675
34.43260105736709
25.80347958756798
36.52652204582466
34.27587052276312
34.118339922234696
30.9423984891407
31.789239129610962
25.381260136034662
21.339302885226886
24.539286926200255
25.590628431970714
23.399446576809783
31.208083453622823
34.52784089038164
31.9463790634615

29.283902003085966
34.69348861831657
33.551211083735964
33.73172595160162
35.009715869253114
34.05130869649932
32.1033601224646
29.084897613879853
33.356162967322234
26.380100003144754
34.79970463049773
33.41515762302722
35.39347706847812
35.23648063982257
30.531118519704755
35.40692216782036
34.84827889896061
33.89007934584121
34.58848948154012
34.723359162858465
34.53182065172646
31.106015321976578
33.161271959646434
35.109355119533916
34.96681144800794
27.07906850623987
36.404464735188434
34.77316177384989
29.270005652595657
33.119637400210046
30.761982295173343
37.27640665132111
36.4114174595458
36.33665716587686
34.58335600794848
32.99821410307851
34.85957446808511
36.31966609804041
37.25951852180865
36.22399557812554
34.99569469011781
27.356356924361307
35.9489174966145
32.75060124308961
35.73909116471681
36.02920610923085
35.056534385343184
34.072885018440594
34.62932628797886
33.19670431430901
31.78514375786235
35.349925411500955
35.035157914080706
34.945835381551866
34.9717678

29.63983916217343
33.536188313557425
33.752627428258734
33.182784810126584
33.972153600673884
33.6219448652895
33.888436429448646
31.780567826212142
29.67108092812677
31.762036742544716
26.200644661552683
31.63292179828498
32.43051990226704
26.176444155973837
33.01951584333793
34.18814342655462
34.43853815142334
35.14436298127278
34.86768862434742
34.009616710047275
33.97710721373891
33.41861873346719
36.14657520079975
32.310354124779494
31.692198420794135
25.226771880864167
26.313569264164318
20.97561024399758
20.761106188776747
19.134249375011404
29.463899855290332
30.493384127722685
30.55113338383544
24.939374479724105
28.740905197519442
32.08076976029126
31.04684076508557
25.732242113400165
26.39039091944404
27.94041940899038
28.82088916374631
24.417145485134796
26.37031448438895
27.164301674168584
31.38485943684947
19.924393499627097
31.456179033733818
29.107907977376037
24.264307904129957
26.920732724868742
27.589930471047143
25.63097493308564
20.822948264135395
30.55135591862303

29.909109708703248
28.027985860057335
31.35576570851867
27.37313919870519
28.282562373567092
24.51132266227201
25.024635009277656
27.71829049887985
31.206690277075086
35.09819082525816
35.83190807739951
24.43407239977164
35.781165490825025
30.253420754621715
28.708249772417712
31.40201245807379
32.3145859656692
30.13798950923331
30.591465060135516
30.737635117804405
24.822626367838268
32.41097287690287
36.011882888297414
31.56697523895537
32.57990197220733
31.721200387221685
30.532674290789178
25.659826989196002
22.04361102205778
30.605528151542572
28.15384821920015
27.563821327883183
28.03416792546152
26.08349346716168
28.143835846233333
33.905695000202094
34.018167661562416
33.45967420265807
34.44589167659015
30.882479843905312
33.38138291098943
34.665101863713375
34.40266408569694
33.99170124481328
22.000482569789032
31.934217538944132
25.837336372316507
33.704890631780266
34.381795527575576
34.654504593826424
34.477887745372044
34.755873018503635
35.21163226071845
33.79668664990653

31.983894828348763
29.965949603126408
34.43118776525444
34.31288398766331
34.73256045048029
33.77409873819321
29.36796924778916
28.909885444093685
23.479743611274387
33.3702283395656
31.851280337778316
26.397200614253705
25.48396582941441
33.04657227724333
29.293105374902225
31.228065995592353
73.84338028169014
58.587029095836066
29.769850451767677
31.013094947612814
19.385495671625925
31.831941956831912
31.936892279812078
28.217678836929245
30.50935436003375
33.8824137652476
33.3925449421206
26.420313316913695
31.827352541678366
27.011579232086966
35.77597707228032
32.70463477013287
29.371465385638857
28.67606057498376
30.586334135491867
37.507413302809724
29.574215747798313
30.254948352472734
27.54300573935199
30.72885255029525
28.804658956679393
26.45948094222738
34.009065183371305
26.5832424895424
29.82764653173847
27.196534865324015
28.96218754315702
23.740492321973363
29.873321795118336
32.552340742580405
34.5338108764563
34.82773395333389
33.80540331420465
32.344738770001925
34.

24.320727365503483
33.035900505663115
32.13188900975991
29.735659645665105
34.55913517789167
29.793957819814317
33.413826617593166
28.061176155750317
31.06454647123738
56.30920831823003
35.42247145463144
31.94929920780012
26.478021804591968
21.31739472948591
25.371894527351145
28.0666216098661
32.128443177988174
37.595159772330035
35.40064651716309
29.42854937730223
28.906498321835436
31.488059578237728
32.077089563082666
30.4807528796192
30.10359652333685
25.423414030961705
34.19316023315534
27.185958180474714
33.37872638431298
30.478316474828507
31.097482131735816
33.45887345740565
26.573137354282817
33.87639324136594
23.720487269683638
35.47730175512793
37.177283968125934
37.361410259836276
33.33866416552075
30.61245283294286
29.880557672990474
31.05856566329742
35.68618175320974
35.39258109157188
28.883407361498467
24.309309779238315
30.674018926706548
33.14528658242653
28.31941771827125
26.34795117753111
34.05047938366118
33.42820709002805
33.49280523836141
32.47395845430825
30.12

22.506219078996793
34.53238926395521
34.867398768008115
34.83207241622721
28.57972989547418
25.97108341228119
35.50162513542795
32.548551562512124
25.288828863592514
34.57451859667634
30.372598573445817
34.20710353545651
27.63300963198187
27.586664123493005
25.563957067367177
33.84577644362674
34.49603579300589
34.53892965076542
32.54930932795282
29.76414652492939
27.855248215175163
29.283697549396077
34.53096776849298
31.40295289149771
28.46065738403496
29.196046220242238
34.63161371292688
29.6530407363941
28.303174260418917
33.652157866444156
25.73855840155132
35.26462526694581
31.75338027102733
30.08826398852224
29.338798693349936
28.328216073105004
34.526419769346646
26.763896244775548
35.160566686226844
30.355452946668308
27.833620895601623
33.73850930677778
27.876168069014103
32.38919820536383
29.618490089046755
28.90072212116201
34.035834848091405
22.630078449568906
26.74665850423426
27.934278616574204
33.734981621639015
26.436799576436773
23.823692461489525
26.457644973474885
1

23.41512214729132
25.502094619654766
26.277959815303266
30.389323209123383
30.434086027747142
29.110332239056653
29.04964539007092
26.858156437101783
21.63384001196635
24.61518237037472
31.54370976475543
32.90734202639301
31.867978573870758
33.15498079142491
32.656000124572756
32.97797696269214
34.334512115258676
33.475162814455366
32.39545229856648
31.396136025091135
26.984816511400485
24.290163602142755
27.520596301982863
26.163055004553563
25.470038135490295
20.556182335903078
25.706377710496316
28.347361804799913
23.535738735200045
25.809354443699196
28.82722786567513
24.343453455370668
24.599590623038893
32.097463917841345
31.451933171360867
23.470677768824423
21.475001408010815
30.047955755192103
27.94116393093157
21.563103751420215
23.332799287939476
22.136918050783496
27.585938373507844
24.807357681502292
28.383425930312033
23.08545512587651
26.989331171254648
20.835567919326394
27.932232285562065
28.063992506105517
28.486172235805487
30.775750994232716
29.705544066404148
20.85

25.851509436288104
23.14073224019597
30.116349536870825
24.300014483937314
25.583292161491215
25.512487682631598
23.36451346955146
30.45640634644011
30.31267345050879
29.863325026699894
29.12913396763664
30.40298063889473
31.77743768467308
30.041714416685767
30.98995153091382
26.53749398931997
29.052462422941055
19.01997542184191
28.408610016120075
24.64903238697469
23.354626041249052
21.223334868211328
24.1053339387008
25.80347958756798
23.501319542110483
23.678305492359023
24.530819213830778
22.54287080979689
29.087116326162636
26.119716029393448
29.113363134075577
33.9237942720339
32.94870304325284
20.69625974538636
30.505360233901115
22.55826861433212
28.063992506105517
26.93560070898302
25.496358795423877
25.90419723807406
25.04705088470473
25.016276697899954
29.82425302558414
27.430783820018966
24.787272770252702
25.990556333577068
30.76852653354656
30.1633477882534
28.35943690922122
18.812165574527825
24.691258020839467
29.576092628372376
24.657871840094064
29.33797782674081
29.

35.94060033761493
34.69434954877454
36.33382421732878
36.41647565465028
36.94836061241389
29.5379761544258
28.526664444912978
24.236686390532544
34.44985256794605
26.660293407236022
27.42181687424406
33.40743926722421
33.32356633244879
31.51266350611199
35.56303205019501
35.69073673820181
35.52718555976249
35.3639337627736
35.10671030274623
34.20431396534149
28.005528587739622
17.173160385856303
22.04337931940612
21.819990323738576
23.864764755082415
19.008597209192715
25.96417030865038
24.231365616370297
21.07595133888417
24.427526440851697
25.99007318085772
33.55819051733794
29.121852998764112
32.09770954979223
29.10285872883708
24.188883378124316
23.775616171235516
16.812657081127014
25.402319595433486
26.892425272174705
21.397763447881804
21.463462561919187
32.41247565763037
33.30028423075091
30.44601559210813
28.70078486919987
27.250604225681542
22.63691806180715
27.845447061635287
27.17574186860179
29.717751420595445
34.47703752414615
36.42659626207184
31.770216633843358
34.22496

22.70849259888902
27.863390265128114
29.965949603126408
30.00689665040278
28.916064005074077
22.16148070653753
30.39637067259959
24.418424852126122
22.18598057677253
23.888823073768624
24.88876229809758
24.58920709365382
24.501299748228547
27.852658560718247
25.30072747891759
27.91512924952746
22.836335126423766
24.324817751074356
29.32013533540251
24.447887340362904
28.965787765362357
23.37050203376609
25.8601164052481
27.746345077596814
25.251831738902702
21.816925877763328
30.522897791361935
29.56525171640844
20.219944657095752
21.684506576226322
27.381895572471244
30.109431307518914
27.69120666547829
29.74536015942471
23.578208883067532
23.48671198665039
29.80348463746696
18.844113775333703
26.59436701878083
16.90569931479242
26.287017886912597
21.505281076314116
25.482107923547066
28.790423107547845
24.870609860950516
27.368138070536034
22.85338171753001
30.748225910503784
25.733189358986944
26.316045726619066
19.858735742660045
29.14492189671466
24.85616588539969
21.6617723767862

28.834362238935256
32.41397857772145
32.708715453241
30.584549869474543
30.26717469114421
26.97700624529673
30.489615817976958
32.25048056960955
32.44005135582471
29.121448607215264
28.846062323335833
33.315360969681564
30.74169030394981
30.353036531002143
29.56671060701119
27.331222061487534
35.179145663314515
30.65877227606976
30.29034447894851
29.164985084797618
20.83246330742295
31.157312969387224
30.06001533709355
34.547464314248764
34.79393099786805
35.10582878569755
30.08847983127569
30.276350931901195
34.478171161766035
31.097021011580836
28.45370671876696
32.63999003906554
32.73475376570671
32.4747127504723
26.206538038588423
33.70895384442284
33.58344809915767
30.640182921929448
26.806830964311278
33.55899602345919
28.796155298479285
28.89833264434339
35.15968246250828
31.582425360490944
30.640406755888026
27.09428696932896
34.47505383768144
29.66688357617768
27.409272994608724
33.07784638922406
28.954390131092993
31.53517187453009
32.11171678814234
30.730653693419104
25.6782

29.827010190512084
29.510543238888616
31.059485637695218
32.18243061789778
31.230158671064682
29.358102290941925
26.490564131066368
36.18711714665332
31.019287658265295
30.26149694809599
27.031076395602128
31.395666005464275
33.767301065919554
27.966687781296883
30.605081505479912
30.96067083973072
28.95279118087625
33.988395838060356
30.351718648237934
30.31333068333755
28.58888563229751
29.20702477612356
34.111402987987866
30.36028693241453
29.84547511634195
29.507013915270214
24.690240585835635
33.924891818659766
34.930992554591334
31.321345361132686
30.859530886724155
27.35582165870966
31.350609551002712
32.34748272458045
32.93059481188367
29.96830477714743
28.652553198756703
33.87694047330587
29.577344014442062
31.089644948484175
28.55365847016856
29.089335376975733
29.610335333568656
34.41536681627596
30.449773131511126
29.90484474706784
28.648052019015353
33.81303408467963
34.8352546427029
31.30778532507278
29.549005241503693
28.092375288003
33.50056309454397
29.026124386682444


28.06680942184154
31.30638323281782
33.45620458334331
29.77048435636818
31.139039021203303
27.28694758345206
32.502394494986284
28.883009564995834
32.69214400960272
29.960384299439266
28.82148329863187
33.50190101920189
23.77319050048178
36.72095323977202
28.634556961161138
31.756024803337397
34.03528247074671
31.158007339504064
30.232050570503905
29.47073165590461
28.5723316711627
31.5695888121994
31.73272000968406
31.17931639434442
29.801155297243913
28.18942133207877
33.24670053980358
30.586780234525406
22.84205596279313
36.15249489298982
32.08224207563334
33.75806062166991
31.092641052061943
30.184403696134027
30.30216159981505
25.61798137120171
30.985372772672203
34.37841382249762
31.818660435900743
29.618908402714517
28.798330174947132
31.57576806968148
29.19279489963529
32.96942256598909
24.118363474310687
36.3074046501965
34.06735002193018
26.244581268458727
34.62017960908611
28.411881456392887
30.829589556627074
33.49788756578895
30.273073064403206
30.808529392321198
30.081574

22.000482569789032
35.84231890002649
34.80692436640056
32.63948203946959
31.290968502409694
28.556185703878704
34.34463332350725
27.98217383182558
32.26859310206876
29.762879282450115
28.221286216038003
30.220070321055967
34.57423359409132
30.639511439675072
27.773536929372657
29.83337482484654
25.26750042169691
36.23056656905681
34.46655490911481
30.708604228899432
28.520845091492646
31.731039543662952
31.56650009031248
30.508244775641725
29.16640473971879
29.180811910808085
33.07393388846833
30.568055272133634
30.215933895728725
30.750029325513196
27.85025431269173
33.413560429230365
23.510804432760274
35.60771529475686
33.60928234879323
29.852697508896796
33.51180498406028
32.677880532593704
30.44933101991332
30.279848106383287
27.87709445223552
30.18592433194913
26.489058424539444
36.086863750559246
32.62678718670753
28.589275368245982
34.21575409515108
30.421945151627245
21.621795499652034
36.19804782905127
35.65311708403461
33.17648547744099
30.673121645141947
30.61133573691048
2

27.351183567003588
25.104318419871316
36.49029518978972
31.263912699950804
33.45967420265807
31.231553943870676
30.409593480609306
27.74561090163392
30.44159614463428
33.06741511025615
30.811471556182415
30.450215255947672
29.977729176494133
28.24884662270924
26.73131683938154
33.785252847453805
33.47142287127923
23.455845920689868
35.90552583144288
31.311524851814802
33.652967889981866
29.12326845763406
32.44180776102779
28.522008772228077
32.90940761082778
30.83298905412657
29.5629594648886
30.179191250539645
27.7368038196511
33.80295129794247
29.892057157110788
33.7518126000853
32.49106444291236
22.644006305742113
37.06590784566712
34.00272391205655
34.34800838574424
32.06286740817185
29.04662774672955
32.962944916419765
29.95781639489454
29.3698200406134
31.98852950373325
28.359053414469237
28.64472596892607
35.57358890632289
33.289976427261834
30.85839568572921
28.603703072254238
25.860913636727975
36.42121898906748
34.24089343151501
30.99590594008188
27.593379121602062
33.1131005

29.84632462819327
30.35830920671685
29.938998536707235
28.56377008989376
33.84577644362674
26.971455028326336
34.56881943757624
27.820328460375155
30.455521750811435
31.711846850593137
32.03813132084696
30.39350724637681
28.163867718650327
29.724701463449204
32.756739870669456
31.240160881870995
30.44800476214674
30.509576286597564
27.408735656219775
32.077580207257846
30.187879660285017
23.220031777139283
35.34813791011066
32.09328874979914
32.86144974772008
33.521982720726335
32.953621571508265
30.00775537653641
27.815716000504015
33.561412773856965
31.969511497976324
30.159877470895744
29.705123302029772
28.638858352394934
31.841366483203643
29.206007896331062
36.765694851072034
27.97060431865772
33.345025241483484
36.28290657439447
32.213079374832
27.65505555006099
28.81831486227438
33.43220386267805
34.02561876870908
31.007133933125846
29.413896602990267
30.890895432249703
28.054606869335473
26.721269072723217
33.853971943758374
34.24257070080334
30.956100729194343
25.178463588721

28.995223117071653
29.66856237444473
31.996826486630813
31.68717042140731
30.92118397287036
27.844153085272346
26.48002777865463
33.48317979339964
33.2327390856509
31.851764098358167
30.336351800954724
26.76475017548338
34.89698895923988
30.860439107657896
30.304350967443607
29.7624568922697
27.98684166627743
33.56678457672423
31.341707453764243
30.422165808370202
28.72929024480458
29.1366209804589
28.468577556658136
34.305587135928285
31.720480688512936
29.441356703143974
25.84832312375975
33.01535724687306
34.35870046037649
28.17749054436256
33.35642824195575
26.826548298997754
34.36320437824641
29.69860297814188
30.701860717056817
29.978371965034913
29.104676256496727
33.29605461617845
27.002710376040532
34.72709659791851
29.06917463111715
28.693912734138767
33.91254851228978
30.83729616068934
30.173329400677662
29.565043315217775
25.81396093105698
34.834965325360244
32.07733488329407
31.277434750186426
30.23030739846481
27.756994996955818
33.28073126606786
26.47869042884289
29.5735

26.09907471360924
32.18267755202259
34.55828094488708
30.419518138698308
30.337448916856534
30.357869747108467
26.90916089793352
31.625766269802373
32.85166909472563
26.643019577452264
33.84768837205549
28.25798193075477
34.78556263269639
30.255384837336795
28.57213703277315
31.33117203256891
27.757362381374666
34.95573760928085
30.09085430596608
30.634364386663258
29.06091680062081
28.285041844531214
34.53068348344393
30.164649363164973
30.482746591470683
27.11705910495623
30.27678803453354
34.935356782915065
27.216300045422102
34.24536651480266
29.20661801570943
27.76195550731065
34.09476584917777
31.147826345259844
30.395930110371115
29.42400752032663
28.0502915841849
34.305587135928285
30.327139159231248
30.577860725533654
28.853602999346474
25.02538155869262
35.04130463841732
34.68516849286748
30.477209146859852
30.593919589192975
26.11597541764475
35.75462884031779
29.997239366913885
30.840470588235295
28.947595812082017
29.018694045856453
32.12745879036706
29.422975475615914
32.

26.94113717530382
34.2107306569224
30.00389149593682
28.17484062955524
33.39573546506999
31.199958343561477
30.500701741628188
28.029484292196553
29.270209915140686
29.863112402190087
34.91034999375754
30.7261512314477
29.18670062488692
40.98361360549536
45.028868347880234
30.89066792361116
30.293626087898595
20.338090181303308
26.118740114331263
33.06741511025615
29.362829380302987
31.506508920187795
29.00203981441146
29.00865908650787
33.70191156500848
27.357605959012222
34.42779633748943
28.670964037432242
29.018694045856453
33.51823230910617
28.747011733742735
31.723599618799824
29.88907495955932
25.757525884621526
33.08123797204783
34.07703744627609
30.931445427728615
30.440712409098168
27.68024180509084
33.359346541425744
29.444043524043526
27.612089452998994
33.791785501361566
28.67919780648073
31.598366707348312
31.907494750935705
31.076514999962953
28.781532845212688
28.878038033075832
32.768256002000015
30.17398060487468
31.371009723261032
29.541096758744064
26.25263039300982

27.120039830075587
34.474203756215836
31.67042193965387
30.593026987600293
30.20440142873603
26.984990124235193
35.05624138075139
26.01021977476807
36.122293608005926
29.31521708742207
28.630256861821582
33.81548756399403
30.303037308903853
30.244040322464343
24.4554423117289
36.56600845647531
33.72630123107355
31.425069303963436
30.083516231297786
36.373210305863175
45.21721881434686
31.34850070256211
31.251566563098404
20.482700356003967
27.486690171304247
27.622454624483023
34.111957838919295
27.467429813819162
36.00631824737312
30.39747213404647
24.734066141435108
35.56484135194261
36.17900148362833
30.971187216634917
23.93053003936783
33.27545062198528
34.981684737281064
27.08291523803989
34.93797584339858
30.367320933398013
28.92284352868974
31.340302321584684
32.159235717626494
30.536897897373173
30.554471746082623
27.29920204110855
29.54296943785086
34.00658353467707
30.361825341672457
30.407388880430922
26.617657511296137
35.15408341155961
31.598366707348312
30.720975030945805

25.53656383373821
31.07237100418565
35.35499098066322
31.133722785947047
28.89614263766698
30.028379558699292
33.36146926178981
27.46113555415881
34.8419102682317
29.363651638196583
27.769491525423728
34.73543685300207
30.153372777661954
30.404964189404705
27.876538614914264
29.650315639160464
34.38856093401548
28.861346214717255
69.89108844897687
30.9679858239811
28.567077365262936
20.1321116065643
31.13580283572118
30.379858324520868
28.993218815884976
28.673708101752155
34.1089063821482
28.86492140831888
31.29353656989801
31.133029497780615
26.31687131769327
35.644936219395085
30.59503541443275
24.015894919466124
35.11699794035399
30.357430300222923
35.60136827005509
31.418007490636704
30.5140154959805
29.716488125602222
28.283325241409074
23.530853254192216
32.985757540010226
35.93628925159577
35.005040894675346
34.88653962920143
35.57871878393051
35.5904929189047
29.99681029858752
24.841003044194117
35.905218463224216
34.64992399709206
29.888223012406204
31.11686153480919
29.23654

28.069251206274636
35.07207064076728
32.01636578756536
30.619827712074756
24.606229136967094
35.53290410030498
34.55657260556128
27.829927278517967
32.901404915242274
29.566502185253068
26.629994349313982
35.79673977980712
29.158902414437964
31.78731176439382
29.755489184798417
27.787336941759474
33.90158422243776
28.109507884701735
33.238796389485444
29.337157006064253
22.091678561458767
37.28336503760067
35.04686781921338
33.4428665970323
30.370839156281907
27.73753752959382
33.842226292390485
28.774227186037898
31.31643433657127
31.435432374499722
28.748982137716425
35.90398904297209
33.45220207047264
32.12868928431906
31.033058095830004
27.641933081581946
27.131969286301096
36.477283796006404
32.70004521853024
29.912949214431915
26.735406228885406
31.479551782886393
34.85291209293436
30.099491919510864
30.037626669531278
28.499140467341157
36.566964830604526
40.60549499486901
43.260316641741014
20.373655091344496
27.758097179388756
35.876042459648794
25.331899935980285
35.463203463

26.30713264256504
34.257393719116266
25.034343627269582
36.47125727154944
34.18145664061545
27.74891499947073
33.86408519502329
28.969989156035666
31.65130248422832
29.92938490081347
28.47514884892428
33.05568778273411
30.905235235604025
30.20200900090009
30.164866303237776
28.01244907500167
33.5689337793927
28.264837290168675
25.011204732344645
36.276316586087304
28.739329738322496
33.9419128774085
27.004970511730924
34.29212417525815
41.43340906845797
44.90689507494647
32.274552351931796
30.320781314383616
20.380981073398285
28.600192290645264
28.98820927500173
33.60335848996139
30.502698064084477
30.773267203239982
22.937492480503998
34.47023726361985
35.68739630218925
35.35379895143209
32.21481128742377
30.841377687579048
29.467004826505736
30.55135591862303
33.63677482477104
30.335474165364808
30.53556400064066
27.728185634482532
33.38510275880733
29.14006224988884
31.268341049210147
29.224933457824104
23.324495061838242
36.61804403624871
36.49601044159234
31.73632160773602
30.714

27.598826114993354
31.036732277638006
23.56324086246222
36.35397923275608
35.15585134025112
32.13188900975991
31.1381143281366
23.51805499484143
34.07094756508671
35.92828569225893
33.12748497365948
31.398721384617687
29.88864897991178
37.092459120776105
27.859133599904354
32.19923077513607
30.647347231051388
27.667460437871462
25.91379992091736
35.91844005035411
34.26103151394357
29.023914968999115
28.9635875232196
34.82310745064178
30.4234898160506
30.293188498956354
30.511351815344774
26.9782208786261
32.11983183109593
31.620044177403184
30.642421408689426
29.208041726728922
28.662734994840534
33.95015500675878
23.257628603589865
37.62281244674076
35.17177070405528
27.770226965756507
76.9187771644446
31.087571061155213
30.04537281785686
19.471801823550166
27.618453109978535
36.74154015960475
30.603071759512606
33.52332235685284
31.886391108340494
25.015530691604837
29.381547147870798
30.895218733196327
34.5676798312125
25.086900610678804
32.815685292690944
34.43316640669896
30.61602

30.060230774743783
27.538484770890374
34.18730743524119
30.840924131237223
30.47455188799198
23.471203133743703
35.311236645591464
34.3319827452136
31.440852154749145
31.392611220884977
30.38756185384019
27.338882407003045
32.77184045005274
31.2993746548662
30.308511637653826
29.628323585092254
28.179762296679005
33.596898479678316
30.928708373890217
29.703230009843704
30.868615502369806
22.276712590688437
36.41615947628433
33.84632268685141
33.34820668983009
29.971731145760387
27.037175032714288
33.42394491903608
31.8723375152929
30.32100050603629
30.90705711569779
27.204296332810127
32.002441592528726
29.782956635352093
33.32647888443049
27.448196429506307
30.175934386128997
27.652320675105486
36.56377711137457
33.4679508150938
28.394762852539365
49.54058395540017
41.303659353212275
30.2481844471849
27.145841693094297
21.603642581947792
26.79073570178464
30.842511636799493
32.110241766318076
31.02364697441511
30.376338011848375
27.466170731068445
33.18961178723472
23.36243121003498
3

27.755709228071336
29.7806305026981
34.278111489772066
30.232486394925576
29.741985349907463
29.768160171470345
28.358861670982616
32.60269415230589
31.69124058360849
30.58544197646098
29.309071597277544
28.129679556825344
34.63876386399861
25.96851066464415
33.64891816219946
30.708379397444816
28.569606975001705
34.38038640294433
30.217675410473838
29.666254075808265
27.482547815774126
30.86225570991288
32.46867936213036
27.491554530140856
35.36482828981206
28.666261148891092
29.19909499112395
31.523558281286405
30.92369169972131
32.32205662500193
30.287500992901656
26.513337884649424
35.80713017347357
30.291875807977583
28.704909730491796
30.802420539333763
28.115160574596302
34.90512054459359
29.88843599464128
30.87066027806605
30.01720460888857
27.220185867815793
34.74435672926383
30.04537281785686
30.086321543085454
29.671290826901718
29.596545203082222
34.14222453764001
27.553862122426455
32.536684508571874
30.883162018083823
27.97918723483737
42.47998703613677
45.99673199030563


29.702388624115684
30.17224412280954
31.533038124093135
27.39602479441407
33.13743057366105
31.36842892506974
30.349961649227918
27.718840043352984
30.128896934172342
33.911451764173215
30.550465798923454
30.79857546719536
30.325385004699587
27.413751633986926
30.86657099753468
33.55738504988439
29.814924863873525
29.773654284355413
28.713556142776948
33.457805856685894
29.23756413116217
28.445023159922144
33.7678447790033
26.581894694146577
35.470401190717816
27.783655597729243
30.93578008718036
32.636180427492086
28.52899285126412
33.65350792733808
31.23899750493427
29.179593852832525
49.13664479850047
35.90552583144288
31.815281454567522
27.783839641764153
21.611434577850144
27.0799426675103
29.06675721938475
33.752627428258734
30.21288672789483
29.46534876042347
30.951303564971628
28.186200917967568
34.01513296082136
30.200269291417957
30.235537517751457
29.819800220397426
26.388066462405707
34.533242217410276
32.05453614471643
30.58075899529729
29.59132502240001
28.64081395745843


27.7770316359711
37.03972164820996
31.037191611537835
28.750952811823094
31.691480037476953
27.49660086928589
34.41734363973545
28.37996901029156
34.52812512862729
27.766550153585424
30.24665753227086
33.476498711000794
28.951592084101247
31.992433430203732
29.39040011211548
27.945818092173205
36.41647565465028
30.872023612368523
30.235973442715128
26.77739472407365
29.898449584773854
32.89779207027727
32.176011660465655
31.003695928565094
30.29121950514928
26.93300627363852
35.01731536676184
26.086738025786307
33.721691590287826
30.849770886811466
39.03166789194018
46.570778233014664
30.556252504280042
30.123919991381477
19.84952556730792
28.031544898013742
34.56198292626652
30.560927982279736
30.190921785698862
29.252041705896712
28.084286929098006
34.655936278681615
30.39460850030798
30.412900980335287
30.373038459588827
26.747681908041578
35.11376403318571
28.1676505154293
32.7536702692572
29.342493161609873
28.505919612880426
33.86326497658647
30.053122962389747
31.034206184193977

25.000619903676505
34.205150788602374
29.491660807200113
33.77328287301715
30.60798493793466
30.731104012191906
30.394828760670755
22.881308406116514
33.305572760334776
34.81067981309497
33.97022758564834
29.872470745760538
28.56863399516398
33.414891413457404
28.85340450999546
31.793335556835753
31.00415428512293
27.258928049184696
33.86189803415008
31.0238764460487
29.925754689384046
29.108514004941288
29.068570240487908
33.30319271416435
30.804456554469407
30.242295767539115
30.43541107321675
27.661439029215856
46.507262768057124
49.911394061997974
30.714900846539148
29.90655058575228
19.24663644206237
31.123788605096394
28.493525903180664
31.010343425381688
30.878387431625598
28.741889947234977
33.08410831617722
30.75453878867869
29.840803665442955
28.859360378708647
29.46555575850393
33.19092498951483
30.599053059318756
30.432098675857066
30.551800997924026
24.869430131690514
33.22931636864914
34.33310686366799
31.34498658555724
29.700495680498513
28.40322340353491
31.964638728213

25.536719311276986
34.04135960783041
32.46340198605274
27.207119783085325
33.6157471227519
22.758765884944708
36.49791592338952
31.719281263234315
34.458343260407
31.923037111456146
27.139693940276295
33.539138153002234
30.99521877609536
29.464520797184424
27.3517186511637
31.281400326663334
35.75523843622662
31.33913147434173
30.514681488810638
30.29012573029732
27.4847088889617
24.666717635366005
33.747739049274244
34.88160739829014
32.66591900311526
28.43133320680025
33.53457952891888
31.268341049210147
28.259885863669744
32.25097653246394
27.61590729523308
32.132135168884496
31.4269529903643
29.098820591091993
31.105553948724793
28.551909108855625
33.609551664730155
24.07102561306651
36.838026313478196
34.171152968780554
45.91365268412295
39.14276648561883
28.93461554381269
28.47456890699253
21.41677474698992
27.221775842262737
32.499372375211145
30.422165808370202
29.534024335286166
31.435903585561817
27.572337628188272
34.12777868185517
30.491167362130884
24.15586719267429
36.879

29.43949688359818
28.446566516328122
33.607935833847485
30.538676607642124
30.54423641302369
30.303037308903853
26.667243122270047
31.815281454567522
33.44553334343378
22.34019185393109
36.738965532343535
32.917155862501964
34.13333333333333
29.1182138790925
31.423185843359953
27.567625833081383
30.57362578086845
33.94356098311038
29.653250380006362
31.44816003359026
28.735588714870993
28.85280905832743
33.87967689822294
30.41995938497244
30.63704958985559
23.87345821309245
36.47760103667499
32.29890881648557
31.935919594928997
30.302818376886563
28.46877078666938
29.49643100768652
33.43860068721947
30.760177477906932
29.382164623467602
31.154998625832857
27.864315799263913
33.61736370485549
30.330209418026147
27.912899962732258
31.946379063461595
20.293022783242293
36.13318515838351
34.137778356556844
34.74435672926383
35.26936983905417
27.6379259220211
33.86053120206668
29.624138320714206
29.758233649766577
30.704782541855476
28.876447504302927
33.476498711000794
29.825313413307356
3

29.216586908518448
30.380738530182967
28.776793616597942
33.50645076250809
30.508022868448233
30.191356425095737
30.33679063779311
27.616270954318598
25.308666111533494
36.42976010561606
32.767232017999575
31.30054253326468
51.532140750933756
37.89474445036726
29.203567673701286
23.777772738610853
25.15008004988877
26.56001215820869
33.36040786784064
30.76739801794268
29.475702228437704
30.073593942696533
28.68057056112471
33.65728867418832
23.76012734595841
36.58482633497898
33.778178655413456
27.395845852384063
33.3739457016455
31.36866352554035
30.344691872494973
29.629998021984232
28.603898140949575
33.45727208187424
28.37804886299822
32.07046733545388
31.04293443266007
27.247240718485074
33.711392242280056
31.05281705782187
22.981606184968246
36.73060048515207
31.58052299097227
33.57699574113804
31.133260590405357
30.395049024225866
30.2604053186347
26.670295361332784
33.78008295413361
31.70992885817753
30.885891016200294
29.032151781326355
28.166137274784607
33.90651727538763
29.

30.268485242115897
31.261815498595034
30.405405013556027
27.428810588820006
33.62113633448762
30.663927534854476
30.48008836695541
28.889176642375986
28.91765890115345
33.61709426370755
30.479645374609404
30.37413823069347
30.423931177554365
21.3783500005097
35.19479081007602
35.04364681505247
31.286300368486224
35.70197734101684
29.37907750499072
35.602577052686975
29.624975278994206
31.309421258108582
30.27875515257394
27.606455519574546
33.71735425576385
30.61289969418514
30.337668349559507
29.122055198750218
28.715718559799537
25.839724001971415
36.98876483764573
33.59447661612642
30.275913841889473
26.659954489404168
32.53643211207732
33.36545009068635
30.179191250539645
29.783379607603656
28.376512932230106
31.78393943756962
29.335720680393912
33.11388487561482
30.409593480609306
27.451070736687786
33.390418265479965
24.181352766183153
32.45561470843135
35.100540612917804
29.69103458039854
33.69189493131979
30.309825770878952
47.855599292600836
37.76440822941521
27.83066592350771

30.377218013528978
31.19531732278194
35.95323161323504
30.985601678449797
30.484740564152137
30.30741661367709
27.17010856891146
29.661428793686266
33.79396361409672
31.41000793805323
29.91465597786162
28.491977447184293
33.042667170857754
31.058795651787566
22.186450002115865
36.33319473319473
33.35987719619181
33.67160920001606
31.00461265523359
26.553622527792548
34.57537363262413
28.61385017362177
34.08839258139497
30.67558929577053
30.183969256897768
32.28101069028946
50.365090420038904
32.920256184854956
29.78486010509871
20.61609846250639
21.788931775560137
36.42121898906748
35.915671935743525
30.88725569612796
28.897735336874668
31.76805095850154
27.586664123493005
34.31091914531593
29.112352765611877
31.803942978465273
29.355636587602095
25.911078438034757
35.302023364643304
32.64684958163067
30.063462710102858
30.63973526382304
21.002078023524227
34.00051880674449
35.855800712960665
36.18742936025193
30.106837790889646
27.992258305636753
34.93157438870011
30.17094189241681
29

26.331244899240378
34.42497065799949
32.037152459517266
31.112475984897376
29.92938490081347
27.394593323623347
34.28651772649614
28.78192785139336
31.850071000615085
29.90441831780232
28.852610579899565
25.573153183913373
36.644277476847805
34.15334505895381
29.46141634940927
28.466838604588027
33.70624492715189
30.42856624661748
29.300267553388426
30.20200900090009
27.24759473277335
33.62814489360679
33.057511487322564
30.399454965826646
29.710594168815344
28.44579481719103
33.259355002418545
22.621900770728498
35.74122298725203
34.88682980386938
28.589080498943495
34.90976886647191
31.24807414360854
30.356771153748724
29.42565894246487
28.32840740240443
33.86053120206668
30.15163866663791
30.502032594230197
29.590907487494974
27.06543889423046
33.16572964851935
32.26412510865468
23.980606504139413
36.549439249893254
30.637273378036845
33.55765353473934
28.77047707240114
31.791166728566772
30.022361244327374
28.276651542833257
33.719251702320946
30.70455776635774
30.27329156682161
36

30.769655131938993
34.06679662118258
30.12500179559003
29.699023557818265
28.374977167714132
33.63974238669265
30.55113338383544
28.915067284359143
31.876697649320942
27.00288421920066
34.50284623737291
30.76852653354656
30.322096511838062
22.96537374887755
35.281830417227454
34.48695938168064
32.807984731391386
30.55736558356404
30.33613238729649
27.312178890270822
30.49670988053776
32.950514961780485
26.892425272174705
34.338166307809445
28.886988023168524
34.101141500536606
30.468574749382537
26.372138352521016
32.978236256132845
23.522275561936382
36.25781466113416
35.259289148929014
32.05061704810301
29.722384421327135
26.49608651981377
34.52300955610611
31.823247344461304
31.25133371084553
30.18961794259062
27.135655504373478
33.91501645494902
29.203974349155068
32.00097659230323
29.64465742193574
28.72142103893614
25.60406314478616
36.509035200724206
33.995558365348764
28.40899485234354
29.591116253474624
33.84031498095914
30.379418240815852
26.269895153511793
34.282594302995626

30.420841915924452
25.56193169352283
36.26941535587974
35.120232443249854
32.77542568238116
26.636589950718893
34.65164157895607
30.50158896379199
30.434969378573708
29.593204075297038
28.37958496004547
33.535383901943696
30.68277017388569
30.804682794988175
29.742196253066897
28.03510483994947
33.61951938953815
23.48447639684433
36.35870629946515
33.56759049547423
28.236105127100387
32.57762450678845
31.671617672599314
30.908423666737903
30.203748910828345
28.033231073593594
33.129578288034246
27.641204420690517
29.45893326216129
34.327206062887726
28.21388259193736
34.521872968056826
30.45264716986612
23.397097051309228
37.78413973893538
30.671327239488118
34.104746184431995
30.5075790637456
30.346448261391753
28.806439427759045
26.91106006749734
33.34794154594749
31.766126161606216
31.247608546651964
30.499149227032767
27.52456950860983
34.091163274595225
28.757457953665043
31.05281705782187
23.734178361249434
36.27882677553562
33.70136997308264
31.833633127651662
31.05672587798864


32.985238720636694
30.874068839619586
29.845687489771088
23.619768437176194
36.33665716587686
35.09907195876116
30.556029898153948
29.933443238344
31.074673087608815
27.29707004048056
34.082852545871184
30.495822942190102
30.501145346258173
29.32095520384766
25.409244562912704
35.37347771817967
33.1287932641423
30.484075877607385
30.526674332959722
22.42175939785314
36.67535828895709
34.192881483051536
34.2009670817127
29.67779916223254
28.42767193292803
33.478636367264514
30.04903211015747
30.748902166342877
29.231043710972347
29.068973164781546
33.088545282423475
30.842284840284723
29.490209313280882
29.933443238344
26.663683059553478
25.766861818784978
35.69590046042161
35.059171647093244
33.25276293465679
26.847497551639602
34.49149699023059
30.530451809202145
30.432981911319754
29.285537735387965
28.670964037432242
32.07905222984497
31.622428130913697
30.730428538981734
29.81958821522011
27.661439029215856
34.36123376889362
24.005173844612962
36.192425510617916
32.46013589858684
2

26.250987313568285
34.596763284227194
31.907737483929374
28.18790575142139
33.523054421061886
23.742642521949314
31.163794960955205
30.10899902371791
34.39702143712378
34.607039720127396
31.39590101351857
30.603741645506815
29.97387302404025
27.4708479061055
32.964499320166304
31.390261791076053
30.428345497018324
29.792053187106674
30.036120937826727
32.29542707106173
35.41110717120038
23.672024562037205
37.932785877075574
35.41708746390151
33.72440299107502
33.41196338811309
32.27480070177599
29.349063403097034
26.97388340461108
35.1673472125567
34.70209984611057
30.37875813916432
30.618933598084446
27.84692603903864
33.373680148316716
30.341179704567484
27.288012751699686
25.16758573100117
35.53139904273794
34.930992554591334
31.767810346133455
30.96844312526765
29.5915337942712
27.68279949575284
34.04246477501461
30.857033554775725
30.346667824300173
29.446937571962145
27.288012751699686
33.31800741935228
33.73335370806759
30.74259160173858
30.286844879626823
21.852959105521197
35.

28.837335936801722
28.97058945419884
33.658639146798485
30.477209146859852
30.69512016627148
28.533844918840224
22.29838542469657
34.33619856901944
34.08839258139497
34.66223709764059
30.32516574965115
29.71354085492852
33.475964339588
29.48274674370708
31.351781256073313
30.448667876588022
27.46329326104607
33.73633833630938
30.51934425275229
30.150338214257474
29.08610777861764
28.944599331989952
25.668149689421988
36.85615367041001
33.927910438102636
30.62519349280061
27.279671158749153
34.52784089038164
31.961228673103154
30.83298905412657
29.521344059911176
28.6396405623724
33.58775104904065
30.00110153427989
30.748902166342877
30.42547604366907
27.431860247614438
33.855611520082654
23.750574751695943
32.97927347067149
33.131410155139186
31.82228156960335
33.677286742034944
31.003466755368297
30.43011158349899
29.374345183068606
26.350930760000253
29.828495028944488
36.388672959466966
31.99462980761896
29.477566625435735
26.73387256120491
36.461745759912375
28.46915725456125
24.51

26.233911471657045
34.30334257509957
28.478048912969676
32.67482569236162
30.54156745381596
27.897119368934945
34.30390368777041
28.50979485854892
32.738841968871476
24.35278201949707
35.638273104995285
33.71274706019467
30.523564171979157
30.6711029535433
25.30286431311986
33.730098352218356
33.38164858691413
32.06850571900422
31.81166191371883
32.30413284246523
28.639445005872233
32.84935347697031
33.48264520867261
30.4603876627668
28.87366450049565
23.358007640644665
36.49823352303382
34.95661160468721
31.389791947313277
31.22504373720454
27.257510869070753
33.671068581566544
30.672448718417492
30.265645858438624
29.43329918176587
24.96639245705306
33.33919416248698
35.16292483358763
31.83556611435381
30.074672135261682
27.837315493256877
26.246552026232134
30.30741661367709
31.160322130100145
33.157339699755724
34.504549268661876
34.24536651480266
30.842738436649753
30.26433555332674
29.801578786565393
27.44496355332208
34.382359209771295
31.046610953611108
30.359847415546533
28.97

27.149707420641086
37.63834274074141
30.872478083895803
30.389323209123383
30.43673623407158
26.573810790947565
36.2719245903057
28.543359760454592
28.521620868098765
34.81154656972594
30.283346088865144
36.04685579724469
23.80908698712563
36.254367236863715
31.55984951091046
30.206359151633
34.25040013065491
30.28400205055632
30.26630105354308
29.073406069344127
28.586352607617023
27.54391011117897
35.46260378443276
32.16934852970502
30.946279558785555
27.035606548923553
34.5093754370953
30.45220497480651
22.650854340829067
36.00539097441004
32.81953692908395
34.15974263957324
30.22072354437311
30.525785650863888
30.344033279073972
26.390723018165115
35.256621695456644
30.804682794988175
30.45154170629533
29.04401296291167
28.838129026491476
33.13193358295022
27.740839704754094
34.44504303265226
24.048667213274545
34.89321486805763
34.05822120811037
30.982626167119726
30.2381532560973
26.669277870681817
33.955651983841065
34.82368569625718
29.463899855290332
31.187430755389
29.9614543

23.546441062376143
35.78910363070097
34.60761081223803
31.528771489352106
28.029296979417268
31.362799566306503
27.78899386486809
32.33950160375031
32.215306153798885
30.313549767280506
31.78538463287283
27.013144929123005
29.927249375668925
34.010719817065755
29.076832421715228
29.544009917727937
22.39123634014702
36.51888936292478
34.71646139584161
34.621608459144674
31.332108227630616
24.3886078451895
34.63990816216975
36.30426202264308
31.28233354962373
29.10972613578002
28.630647726574605
33.3973309551868
30.412018910061196
30.61021872240427
30.5204546446815
27.187015478752365
25.999900818249444
36.64171646224272
34.059880628527345
29.091352989727906
28.89176361995688
33.71843848479002
30.44623659816639
30.595704948646127
30.1299790958788
25.17680108527318
34.22133742371332
33.44740031897927
30.56382304289847
29.496845880656846
28.66959220221739
32.898050104318635
23.420221230784694
35.98685553963501
34.71703610508716
28.94000593385818
33.7425806295906
30.49028074613629
30.4991492

28.784693198273317
30.222030075729737
33.996109454026715
22.67411964407348
34.826577212415096
35.33176090033021
27.83288209375166
25.89172438485376
34.7919106790318
34.913255920422856
30.269795906584683
29.670871032321504
34.02837926642274
28.904107889822274
31.873548543984437
30.937149179420985
27.48128734668204
33.92873379118434
30.678057343475718
21.843399282355207
29.173099260640036
35.86438533035768
36.24089722985467
35.07412362857907
30.56493667380817
30.13019553754867
23.12134241802827
34.90163511545663
30.749353020094865
33.990599371130344
26.877777136961633
32.07071255438398
33.630301961224525
24.090519568538706
35.18888534657785
27.24794875626092
35.799489591246235
34.966228439472125
31.0539666086699
30.44159614463428
23.460569076132252
33.34926730752411
34.474203756215836
31.716882684774884
31.189054134443783
30.25211150780771
27.189306573838184
28.996425830804224
33.75887575155139
32.51020423981708
29.78951405559738
22.571136439464876
35.24625210084034
34.672552472120955
30

28.08729600685725
37.86019641825534
28.24447138047138
34.6090386249804
33.509127659404484
32.346734327161116
23.418259782026084
27.163949820927808
38.28841115523301
37.438780337585136
37.4167372900256
32.116388584730124
28.071505538265903
33.30610170568243
32.14715801091422
31.108783848932337
29.09054591104237
28.61014174431454
30.445352593184044
33.604435399875015
29.90655058575228
30.874977916494906
27.476966616005452
25.703699618210678
36.573660850533216
34.03693965657156
29.26796318393379
29.019296364202443
34.865659731169835
31.452169022533838
30.753411298896506
30.574517250679747
27.39566691269162
31.149445603820247
32.62704098698591
30.667066367378574
29.622882971961296
28.289429666001187
34.03003578006215
23.421529045840103
35.78849287951057
34.945835381551866
27.946376695717063
33.71545702274061
30.625640726083212
30.52511917324697
29.027932342275005
28.82722786567513
33.84277242102715
30.228346570188968
30.645331930501367
30.150338214257474
26.6575823058345
33.68513030558567


26.585432948588743
31.451461479626268
33.11754534185031
30.378098066198305
24.657002104570093
36.37920446857599
29.80242580131735
30.634811887841185
32.98005142439278
31.088953621963785
30.400115967239255
27.55150917988636
33.22457838578592
30.8863458961104
27.96463669942528
31.78201271491464
28.677433029304378
33.05073874157834
30.434527696750692
30.9707298343031
24.068677408988663
35.33563046023976
34.70956636875207
31.40671518854644
30.16508324643101
29.559209274463512
25.54402889177157
25.001663080215305
33.966926353638584
34.305587135928285
35.070604368039064
29.87204523926529
33.63461692675338
30.67222441607067
28.249036881381503
30.095388434851866
25.23739725862546
35.82027960680826
35.069724663249694
32.59534652388132
30.451320623212187
23.706811964459316
33.69974530174111
34.979642556314474
32.095253399447515
29.520097407853157
28.1385491650957
32.34199528090927
28.33721134487278
35.869599425307015
30.635483164122416
27.736436979235553
26.55110115147717
36.42280037514328
33.90

30.671327239488118
35.8450757187297
31.315265271991517
30.51556952447471
27.256448080684677
25.96240243140022
36.75860618383229
30.4807528796192
32.058456199888404
29.016084288590186
33.91693621425799
30.411577894110994
30.212669096566927
30.775750994232716
27.204296332810127
33.82448670182739
30.81486705898775
29.815984588371613
29.83464807767543
28.37017897485153
33.380585908588074
22.177651581246067
35.330570437009335
35.147897061164976
30.5204546446815
33.32171315532322
32.26462149126518
30.37567804404661
28.07789477912184
30.024080516542828
33.81657811353613
30.752058420277
30.241641611328618
30.43519022429269
25.86346510781829
31.068458245063034
34.4184733551066
24.549053577908623
35.51695697458783
31.225276197849976
32.24031669164841
32.18020838128558
29.07219696129533
31.915749745088192
27.382610625824228
34.00658353467707
30.638168563456002
30.427021066682144
29.290241483819607
28.133453174677705
34.16781257127961
30.594365909521933
30.585218944835383
24.00984595657475
36.3536

30.143620996952798
37.15225652154657
30.664375900161573
23.94460143748537
35.403335809305155
34.76422710319105
30.116133294081322
24.19795422683505
32.28498633722049
32.55158283598885
34.97118463180363
30.583434808922075
30.03827202933425
30.630337464307363
24.70827614239513
34.63790568998266
34.21407945183131
30.24447649264494
28.834164014216675
23.019697593370104
36.363119337639255
32.32778647017565
35.37019640251975
30.82256630339729
26.58863503816213
34.387433181385894
29.93365686554382
28.673316060405117
26.862972902002728
33.99280318993743
31.493733997101646
32.716879875195005
30.27198059962181
30.037196445068282
27.986654922998905
23.76174262810526
36.3643804024588
35.422172301091976
27.53143502290838
31.39778120461725
30.80377785285175
33.81330667591077
29.298630175262126
31.542049257379208
27.952895387506747
33.13010165796479
30.752058420277
30.02558504126966
29.533400460501763
28.41688629326757
35.224052068024356
24.06660584465139
36.46237970634003
34.11500984171913
28.327833

30.28597010614485
25.292488783829416
36.23682687240274
33.90871020421363
28.692146145584644
33.60120487718905
30.68995441474533
28.469736976073307
27.332468801928904
33.34688101257772
35.87788375176425
31.178852844102167
30.83321571394966
30.264553929633156
27.11162535147539
33.17543582117885
31.547505866778987
23.822068746166256
36.38488497172005
31.118708452041787
31.779363852646572
29.256122484567364
32.768256002000015
31.18070712777662
27.10146482040281
33.80567578241491
31.010343425381688
27.714993689580208
28.66939623647462
32.03519491628987
35.542840678942774
32.279520075113325
32.377946920689816
24.872822155013935
37.44279095510583
34.86247194746904
30.840243821736603
30.573180065457144
28.521426919990752
28.924838111263593
34.128056371492036
30.560037304733036
30.11137673824241
30.643988544041147
28.022368166117708
33.31403790249559
30.690403541506605
30.337448916856534
29.039790075675228
22.554750727303038
36.05584210164363
35.20483464831291
33.28337221666746
30.6767110864063

26.839079577158362
34.08257559136377
31.237136282052237
30.292313358996395
29.214551887942385
28.50107703702697
25.34812773466773
34.53096776849298
35.134942241805376
31.806113550363612
27.546442668277916
33.84168018137955
29.571505118587666
25.03240130106532
31.512426746806913
33.74013771799987
36.049954016863346
31.429072407514255
30.529562907158713
29.12569527870173
26.613604060913705
33.6845892528731
25.812848869769645
36.351143582676826
31.98267540013573
27.503091742457524
35.09055618767151
29.100839519877887
32.25023259390258
30.26280700741724
27.668373001213784
33.356162967322234
30.918448734676428
30.536230934439956
27.82734232979048
25.304085523299307
34.83178315174063
35.24891798539385
28.55599128540305
37.76712859162412
29.346599217760613
30.470124152760928
36.834791161695996
32.68602956647782
27.880059292347166
30.61312312969856
34.09254879010299
30.856352534392702
21.844423149035457
35.31837281170794
34.95020331977868
33.48531830302256
31.111091331211938
30.324508003528205

26.837362271732594
35.53079705541013
31.913807009267572
30.610442118783844
30.29625188705821
27.74707929241476
33.07054380307343
29.101647169837502
31.57339114593919
24.72706692449182
35.9452205063161
33.12774662348946
30.658548173704563
30.38558057318381
28.182791869645555
30.95792861149656
32.72428240397594
29.475495087773545
31.760353170125928
29.549005241503693
25.758158615522557
34.553156433555486
34.011547194291275
30.290563230759233
30.688831655350036
22.52144590734337
37.67079512488661
32.48879938032533
32.669735561007904
30.05376898824878
28.044664946041
33.85205930541319
30.442921844152828
30.624075466738706
30.154890288442182
27.826788474679724
33.21721087519502
30.855671544069505
30.01505653356233
29.685570913929407
27.628823060556357
20.802602864738326
35.66312101964986
35.51545326762519
36.23682687240274
30.896584237549078
33.93861714609378
29.052261188188762
31.53066762890628
29.80666159739051
28.222615482959323
33.510466268256046
30.323192596876808
30.358748679048624
29

28.37516912918764
32.80003128054741
29.471145806252153
28.229833688928974
33.58398590759869
30.70703047784993
30.260187002193234
30.062169852566996
27.934278616574204
33.28495698822334
31.02364697441511
29.729968812021546
30.043220709266595
27.510307418849163
32.364955167677515
32.06556374422801
30.42172449808518
29.874811248183708
28.122512471168804
32.68424661804127
28.681551180617763
32.94973840086728
29.49850548925007
27.367602343760197
34.65679534637758
29.786552282475924
31.67879396681294
29.403792632058607
27.59864451390031
34.64706173900114
30.468796083074846
30.28312744128286
29.316036680832028
27.61136236463579
33.20958368303536
32.06752500076455
30.18158006461873
30.422386468314123
27.694314955430837
33.35722409117299
29.129943188921146
32.03617365800006
23.744927536231884
37.89166335417194
35.545852860665946
30.090638429144338
30.418856293287885
29.308252393263924
27.985907974805166
32.71177663391047
31.305682233782907
30.407829774893973
28.841103501389004
24.50702612374158

29.918923738667086
27.203767001122056
34.367709477065276
30.972788161188607
30.16356470960504
29.3696143854465
27.456281953090734
33.323831088865056
31.965369548981055
30.497596870478226
30.277443712146916
27.693217832241707
32.58293908814779
29.18852864012471
32.37045040595191
29.997239366913885
27.842304756214943
33.80840070610426
30.68591286534733
30.21811082052723
29.90079416000114
27.729468854539924
33.97050271728126
30.596374512163987
30.273073064403206
29.30804759941584
26.741713156300808
34.328891798985104
31.423892114628206
31.03168050191622
30.04515759312321
27.93539492350626
32.95388048209431
28.61092238638999
32.63059460552828
29.553794012161696
27.464731920689385
34.43005721509428
32.47571853320119
30.096684151233127
31.06891851851852
29.906763829271423
33.4946774953483
29.720278332837324
30.298659269533054
30.03547567045007
24.396268118470953
31.92765416498565
34.802880945268676
33.763767357617226
30.472116474383192
27.388690087501633
33.87447806879396
27.820328460375155


27.14408490810251
34.32467776913949
31.416360190851417
32.01856545238022
31.08089041704953
26.614279550242394
34.004102248129264
29.293105374902225
32.132135168884496
29.135811388122843
28.419774501300953
33.55174786017118
31.003466755368297
30.12305460395435
30.18961794259062
28.04054017916834
33.329391945583424
30.8699786560683
30.0126940057674
29.543801815889385
27.666912928759896
32.218523155865206
32.76185715178404
30.18853149269093
30.110079756495022
28.09500971263983
33.16205852354936
27.67311930116253
33.06715441257628
29.43453851336178
26.316541075047528
36.36406512805396
28.02367875993853
33.874204490389275
29.54567483798253
28.39360953154617
33.62868413456913
31.06109572403987
30.023220855821677
29.21577286626777
27.582128812489312
34.32776795652459
31.11478401495538
30.400997347172492
30.50158896379199
27.547528192464057
32.954398315471884
28.81118842690223
32.51826984951505
29.716067051138538
28.143835846233333
32.053066371174204
30.92186785803807
29.082679240049924
31.336

29.9432732464751
30.049247390404137
27.783287516974134
32.61917501399863
32.357215043394405
30.406066273750753
30.246003187354425
23.162840528167266
35.727827183208966
35.669793429545784
30.981253046933862
29.01046486695855
28.543359760454592
33.2796750031738
30.158359458137998
31.173754700994454
30.169422765689625
27.628277079545754
32.31906794680146
30.926883940421767
31.026400858083367
29.05065141052369
28.541611660791812
33.66296138751334
30.95541532897893
30.245785078673723
30.230089516094157
28.00964305986844
32.0562510508858
31.416595508816084
30.183534830166955
29.91038943442512
27.71993919767365
34.289040401563085
30.384700086931325
30.196573074154067
31.506272253353966
27.70565698734378
33.02341547909614
30.98514387027666
30.09841194663911
29.213534483959492
28.61014174431454
33.30821765509355
30.86248280023252
30.257349175088912
30.141238187632496
27.418590208729643
34.15918623307028
30.081142914518082
31.04546194726947
29.344340744679364
28.54666231079168
32.86144974772008


24.9289985141159
29.38545826502445
24.554514799550393
25.988301774561318
26.36915397237538
25.323335144599408
18.514792220289753
29.31009566669695
27.505436422060463
21.82816638997455
26.797582386690348
29.54817257023699
21.628039127722
26.318522655254853
29.78274515373145
28.54860534447787
28.738738985652226
22.961224947856504
21.553242001623826
25.65857120135074
22.674732534315076
24.646425234605914
20.036707415528518
20.150681969953926
23.704936192338558
27.763793183337636
25.98089669098973
20.93791464699158
28.354260605036337
23.00391597652608
22.02289290739924
27.229374951310085
26.164523876360686
25.48845688727918
27.454484758432447
26.586444051444907
25.47112085456279
25.57627201326894
29.154646054607127
32.73603121951219
32.32579325014836
30.623628279170287
27.89600611885205
27.08239061935017
22.369263425118532
26.36749627524816
30.116349536870825
23.551597506878544
31.768532194172405
25.31477614282438
23.783031010960723
27.64739926305312
22.52168776915064
22.252366198378677
21

26.640988833699616
20.63029492199028
29.70533368272697
29.608872134804493
30.313111602561325
26.505798118060426
27.85691324734668
30.27023281996507
30.70770492283363
30.563154903303847
25.84880102056538
31.64628745180591
26.222266680004
29.810474843460153
28.928229533071246
31.02571234133207
32.00024414248766
32.46591480830708
32.869690605310176
32.5028982362605
30.26062363822634
30.86634384704826
26.456977411643003
26.99349989059222
28.279701985638674
24.130990599146212
24.347834163444904
29.988874747965852
32.404212087733804
31.741845646218348
26.71105874860691
20.76490915391851
29.922765764673148
34.255155460091636
35.453910720776314
35.86377200707989
34.94059529660699
34.51448696954486
27.70181429109234
33.07915076185369
32.83572368009018
32.447078117989264
28.487720060856336
33.478636367264514
36.71613151720999
25.61438307643452
21.95361496548078
24.975163601069436
32.83469547518397
25.761006289308177
27.14127452502977
23.51976941754378
25.99410000247899
32.6443086741643
26.982733

In [16]:
cv.destroyAllWindows()
cap.release()

In [14]:

# import the necessary packages
from __future__ import print_function
from imutils.video.pivideostream import PiVideoStream
from imutils.video import FPS
from picamera.array import PiRGBArray
from picamera import PiCamera
import argparse
import imutils
import time
import cv2
 
# construct the argument parse and parse the arguments
ap = argparse.ArgumentParser()
ap.add_argument("-n", "--num-frames", type=int, default=100,
	help="# of frames to loop over for FPS test")
ap.add_argument("-d", "--display", type=int, default=-1,
	help="Whether or not frames should be displayed")
args = vars(ap.parse_args())
 
# initialize the camera and stream
camera = PiCamera()
camera.resolution = (320, 240)
camera.framerate = 32
rawCapture = PiRGBArray(camera, size=(320, 240))
stream = camera.capture_continuous(rawCapture, format="bgr",
	use_video_port=True)

usage: ipykernel_launcher.py [-h] [-n NUM_FRAMES] [-d DISPLAY]
ipykernel_launcher.py: error: unrecognized arguments: -f /home/pi/.local/share/jupyter/runtime/kernel-be28345d-b3be-4725-bffc-ca38ca5744db.json


SystemExit: 2

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:3334: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)
