In [1]:
import picamera
import picamera.array
import cv2
import numpy as np
import time

THRESHOLD = 60


            


In [21]:
def testc():
    with picamera.PiCamera() as camera:
        camera.resolution = (640, 480)
        camera.framerate = 24
        # Give the AGC some warmup time
        time.sleep(0.1)
        with picamera.array.PiRGBArray(camera) as stream:
            while True:
                camera.capture(stream, format='bgr', use_video_port=True)
                cv2.imshow("slika", stream.array)
                hsv = cv2.cvtColor(stream.array, cv2.COLOR_BGR2HSV)
                print(cv2.waitKey(1), "da")
                if cv2.waitKey(1) != -1:
                    print(cv2.waitKey(1), "asf")
                    return

In [24]:
# import the necessary packages
from picamera.array import PiRGBArray
from picamera import PiCamera
from threading import Thread
import cv2
class PiVideoStream:
	def __init__(self, resolution=(320, 240), framerate=32):
		# initialize the camera and stream
		self.camera = PiCamera()
		self.camera.resolution = resolution
		self.camera.framerate = framerate
		self.rawCapture = PiRGBArray(self.camera, size=resolution)
		self.stream = self.camera.capture_continuous(self.rawCapture,
			format="bgr", use_video_port=True)
		# initialize the frame and the variable used to indicate
		# if the thread should be stopped
		self.frame = None
		self.stopped = False
        
	def start(self):
		# start the thread to read frames from the video stream
		Thread(target=self.update, args=()).start()
		return self
	def update(self):
		# keep looping infinitely until the thread is stopped
		for f in self.stream:
			# grab the frame from the stream and clear the stream in
			# preparation for the next frame
			self.frame = f.array
			self.rawCapture.truncate(0)
			# if the thread indicator variable is set, stop the thread
			# and resource camera resources
			if self.stopped:
				self.stream.close()
				self.rawCapture.close()
				self.camera.close()
				return
            
	def read(self):
		# return the frame most recently read
		return self.frame
	def stop(self):
		# indicate that the thread should be stopped
		self.stopped = True

In [25]:
# import the necessary packages
from __future__ import print_function
from imutils.video.pivideostream import PiVideoStream
from imutils.video import FPS
from picamera.array import PiRGBArray
from picamera import PiCamera
import argparse
import imutils
import time
import cv2
# construct the argument parse and parse the arguments
ap = argparse.ArgumentParser()
ap.add_argument("-n", "--num-frames", type=int, default=100,
	help="# of frames to loop over for FPS test")
ap.add_argument("-d", "--display", type=int, default=-1,
	help="Whether or not frames should be displayed")
args = vars(ap.parse_args())
# initialize the camera and stream
camera = PiCamera()
camera.resolution = (320, 240)
camera.framerate = 32
rawCapture = PiRGBArray(camera, size=(320, 240))
stream = camera.capture_continuous(rawCapture, format="bgr",
	use_video_port=True)

# allow the camera to warmup and start the FPS counter
print("[INFO] sampling frames from `picamera` module...")
time.sleep(2.0)
fps = FPS().start()
# loop over some frames
for (i, f) in enumerate(stream):
	# grab the frame from the stream and resize it to have a maximum
	# width of 400 pixels
	frame = f.array
	frame = imutils.resize(frame, width=400)
	# check to see if the frame should be displayed to our screen
	if args["display"] > 0:
		cv2.imshow("Frame", frame)
		key = cv2.waitKey(1) & 0xFF
	# clear the stream in preparation for the next frame and update
	# the FPS counter
	rawCapture.truncate(0)
	fps.update()
	# check to see if the desired number of frames have been reached
	if i == args["num_frames"]:
		break
# stop the timer and display FPS information
fps.stop()
print("[INFO] elasped time: {:.2f}".format(fps.elapsed()))
print("[INFO] approx. FPS: {:.2f}".format(fps.fps()))
# do a bit of cleanup
cv2.destroyAllWindows()
stream.close()
rawCapture.close()
camera.close()

# created a *threaded *video stream, allow the camera sensor to warmup,
# and start the FPS counter
print("[INFO] sampling THREADED frames from `picamera` module...")
vs = PiVideoStream().start()
time.sleep(2.0)
fps = FPS().start()
# loop over some frames...this time using the threaded stream
while fps._numFrames < args["num_frames"]:
	# grab the frame from the threaded video stream and resize it
	# to have a maximum width of 400 pixels
	frame = vs.read()
	frame = imutils.resize(frame, width=400)
	# check to see if the frame should be displayed to our screen
	if args["display"] > 0:
		cv2.imshow("Frame", frame)
		key = cv2.waitKey(1) & 0xFF
	# update the FPS counter
	fps.update()
# stop the timer and display FPS information
fps.stop()
print("[INFO] elasped time: {:.2f}".format(fps.elapsed()))
print("[INFO] approx. FPS: {:.2f}".format(fps.fps()))
# do a bit of cleanup
cv2.destroyAllWindows()
vs.stop()

ModuleNotFoundError: No module named 'imutils'

In [2]:
import io
import picamera
import cv2
import numpy

#Create a memory stream so photos doesn't need to be saved in a file
stream = io.BytesIO()import time
import picamera
import picamera.array
import cv2

with picamera.PiCamera() as camera:
    camera.start_preview()
    time.sleep(2)
    with picamera.array.PiRGBArray(camera) as stream:
        camera.capture(stream, format='bgr')
        # At this point the image is available as stream.array
        image = stream.array

#Get the picture (low resolution, so it should be quite fast)
#Here you can also specify other parameters (e.g.:rotate the image)


#Convert the picture into a numpy array
while True:
    with picamera.PiCamera() as camera:
        camera.resolution = (1640, 1232)
        camera.capture(stream, format='jpeg')
    buff = numpy.fromstring(stream.getvalue(), dtype=numpy.uint8)

    #Now creates an OpenCV image
    image = cv2.imdecode(buff, 1)
    cv2.imshow("img", image)
    if cv2.waitKey(1) != -1:
        break
cv2.destroyAllWindows()

cv2.imwrite('result-1640.jpg',image)

/usr/lib/python3/dist-packages/ipykernel_launcher.py:18: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead


True

In [12]:
import time
import picamera
import picamera.array
import cv2
import numpy as np

def fun():
    with picamera.PiCamera() as camera:
        camera.start_preview()
        time.sleep(2)
        with picamera.array.PiRGBArray(camera) as stream:
            while True:
                camera.capture(stream, format='bgr')
                # At this point the image is available as stream.array
                image = stream.array
                cv2.imshow("img", image)
                if cv2.waitKey(5) != -1:
                    return





# Create the in-memory stream
stream = io.BytesIO()
with picamera.PiCamera() as camera:
    camera.start_preview()
    time.sleep(2)
    camera.capture(stream, format='jpeg')
# Construct a numpy array from the stream
data = np.fromstring(stream.getvalue(), dtype=np.uint8)
# "Decode" the image from the array, preserving colour
image = cv2.imdecode(data, 1)
print(image)
# OpenCV returns an array with data in BGR order. If you want RGB instead
# use the following...
image = image[:, :, ::-1]

[[[21 25 14]
  [30 32 26]
  [33 33 39]
  ...
  [39 37 43]
  [39 36 45]
  [37 34 43]]

 [[33 33 27]
  [36 35 31]
  [37 35 41]
  ...
  [44 37 44]
  [45 37 47]
  [39 31 41]]

 [[43 35 36]
  [47 41 42]
  [45 41 47]
  ...
  [53 41 47]
  [51 38 46]
  [52 38 49]]

 ...

 [[43 35 42]
  [42 34 41]
  [39 31 38]
  ...
  [37 33 39]
  [41 33 43]
  [35 27 37]]

 [[39 33 38]
  [35 29 34]
  [32 25 32]
  ...
  [38 31 38]
  [42 38 44]
  [40 36 42]]

 [[32 28 33]
  [33 29 34]
  [33 29 35]
  ...
  [40 33 40]
  [36 32 38]
  [39 35 41]]]


/usr/lib/python3/dist-packages/ipykernel_launcher.py:31: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead


In [1]:
import io
import numpy as np
import picamera
import picamera.array
import cv2

cami = 0
def fun2():
    stream = io.BytesIO()
    with picamera.PiCamera() as camera:
        cami= camera
        camera.resolution = (640, 480)
        camera.start_recording(stream, format='h264', quality=23)
        while True:
            data = np.fromstring(stream.getvalue(), dtype=np.uint8)
            print(data)
            image = cv2.imdecode(data, 1)
            print(image)
            return
            cv2.imshow("img", image)
            if cv2.waitKey(5) != -1:
                camera.stop_recording()
                cv2.destroyAllWindows()
                return   
fun2()


[]


/usr/lib/python3/dist-packages/ipykernel_launcher.py:15: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  from ipykernel import kernelapp as app


error: OpenCV(3.4.3) /home/pi/opencv-python/opencv/modules/imgcodecs/src/loadsave.cpp:737: error: (-215:Assertion failed) !buf.empty() && buf.isContinuous() in function 'imdecode_'


In [4]:
with picamera.PiCamera() as camera:
    camera.stop_recording()

PiCameraNotRecording: There is no recording in progress on port 1

In [22]:
from picamera.array import PiRGBArray
from picamera import PiCamera
import time
import cv2
import numpy as np
from fractions import Fraction

camera = PiCamera()
#res = (1640, 1232)
#res = (640, 480)
res = (1280, 960)
camera.resolution = res
#camera.framerate = 30

time.sleep(1)
camera.iso = 150
t = camera.awb_gains
print("t=", t)
camera.awb_mode = 'off'
camera.awb_gains = t
#camera.digital_gain = Fraction(1, 1)
camera.drc_strength = 'off'
camera.exposure_mode = 'off'
rawCapture = PiRGBArray(camera, size=res)

time.sleep(0.1)
n = 0
t1 = time.time()
averf = 10

for frame in camera.capture_continuous(rawCapture, format="bgr", use_video_port=True):
    """
    img = frame.array
    hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
    low = np.array([0, 120, 80])
    high = np.array([180, 255, 255])
    mask = cv2.inRange(hsv, low, high)
    #image = cv2.imdecode(image, 1)
    #print(image.shape)
    #cv2.imshow("Frame", img)
    #cv2.imshow("Frame2", mask)
    #print(camera.iso, camera.digital_gain, camera.analog_gain)
    """
    key = cv2.waitKey(1) & 0xFF
    
    print(1/(time.time()-t1), end = '\r')
    #averf = averf*0.9+0.1*1/(time.time()-t1)
    #print("average = ", averf)
    t1 = time.time()
    rawCapture.truncate(0)
    
    if key == ord("q") or n>50:
        break
    n += 1
    

cv2.destroyAllWindows()
camera.close()

t= (Fraction(167, 128), Fraction(5, 2))


In [74]:
camera.close()
cv2.destroyAllWindows()

In [39]:
import io
import time
import picamera
with picamera.PiCamera() as camera:
    stream = io.BytesIO()
    for foo in camera.capture_continuous(stream, format='jpeg'):
        # Truncate the stream to the current position (in case
        # prior iterations output a longer image)
        #img = foo.ar
        print(type(foo), foo, type(stream))
        #mage = cv2.imdecode(foo, 1)
        file_bytes = np.asarray(bytearray(foo), dtype=np.uint8)
        print(type(file_bytes), file_bytes)
        #img = cv2.imdecode(file_bytes, cv2.IMREAD_COLOR)

        cv2.imread(foo)
        stream.truncate()
        stream.seek(0)
        if process(stream):
            break
            
image_stream = io.BytesIO()
image_stream.write(connection.read(image_len))
image_stream.seek(0)
file_bytes = np.asarray(bytearray(image_stream.read()), dtype=np.uint8)
p
img = cv.imdecode(file_bytes, cv.IMREAD_COLOR)

<class '_io.BytesIO'> <_io.BytesIO object at 0xa26549c0> <class '_io.BytesIO'>
<class 'numpy.ndarray'> []


TypeError: bad argument type for built-in operation